### ISSUE TITLE
Local compose bind mounts on windows don't resolve relative path properly

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1102]
from @chris-crone brother, it seems a compose file of the form 
```
services:
  one:
    image: alpine
    volumes:
    - $PWD/something:/something
```
the bind mount is not set properly on windows.
