### ISSUE TITLE
Introduce "event queues" in compose model

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1127]
**Description**

Introduce `Event Queue` type in compose model so we can model event streams in a compose application.
This is a required backbone for Lambda support, which also could make sense for "classic" compose applications

We don't want to jump into a debate by compose-spec without an initial spike and concrete implementation to discuss the abstraction and syntax, so this has to rely on extension fields, and types will be later moved to compose-go

```yaml
x-queues:
 my_event_queue:
   name: "foo_bar" // overrides name set by key, like we do for networks/volumes
```
