### ISSUE TITLE
Use Amazon SQS to implement queues

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1128]
**Description**

Add support for queues on ECS using Amazon SQS.
This includ support for user-defined queues using `external`:

```yaml
queues:
  my_events:
    external: true
    name: "arn:sqs:1234abcd"
```
