### ISSUE TITLE
Add support for AWS event triggers using "driver"

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1129]
**Description**

AWS lambdas can be triggered by events which are not actually sent to a physical queue
Using `driver` and `driver_opts` to mimic volumes/networks we can express alternate event sources.
For demonstration purpose we will first support S3-file events as:

```yaml
x-queues:
  my_events:
     driver: "aws-s3"
     driver_opts: 
       - bucket: "arn:s3:1234abcd"
```
