### ISSUE TITLE
Introduce "functions" in compose model

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1131]
**Description**

Introduce Function type in compose model so we can model "lambdas" in a compose application.

We don't want to jump into a debate by compose-spec without an initial spike and concrete implementation to discuss the abstraction and syntax, so this has to rely on extension fields, and types will be later moved to compose-go

```yaml
x-functions:
  sum: # this is the name for my lambda
     src: ./sum/  # path to function handler / project
     lang: javascript # language / technical stack that will define packaging as a container
     consume:     
       - source_event_queue
     produce: 
       - target_event_queue
```
