### ISSUE TITLE
docker compose overlay not concatenating compose top level extensions (for AWS ECS)

### ISSUE THREAD

**Issue by anshrma** [docker/compose-cli#1212]
**Description**

**Steps to reproduce the issue:**
1. Create a file like docker-compose.yaml

```
services:
  yelb-ui:
    image: yelb-ui
    depends_on:
      - yelb-appserver
    ports:
      - 80:80
    networks:
      - yelb-network

  yelb-appserver:
    image: yelb-appserver
    depends_on:
      - redis-server
      - yelb-db
    networks:
      - yelb-network

  redis-server:
    image: redis:latest
    networks:
      - yelb-network
    # uncomment the following lines if you want to persist redis data across deployments
    volumes:
    - redisdata:/data

  yelb-db:
    image: yelb-db
    networks:
      - yelb-network
    # uncomment the following lines if you want to persist postgres data across deployments
    volumes:
     - postgresqldata:/var/lib/postgresql/data

networks:
  yelb-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution

# uncomment the following lines if you want to persist redis/postgres data across deployments
volumes:
  redisdata:
     #driver: local # you can pick another driver depending on the platform you are deploying onto
  postgresqldata:
     #driver: local # you can pick another driver depending on the platform you are deploying onto

```

2. Create another file named docker-compose.prod.yaml . Replace 'vpc-0ef709490b6edce0d' with any other VPC in your AWS account. You can create a new VPC in your AWS account using [this quickstart](https://aws.amazon.com/quickstart/architecture/vpc/) if required.

```

x-aws-vpc: "ENTER YOUR VPC ID"

services:
  yelb-appserver:
    deploy:
      replicas: 3
      x-aws-autoscaling:
          min: 1
          max: 10 #required
          cpu: 75
```
3. Create AWS ECS context using credentials of your choice. 

```
docker context create ecs ecs-us-east-1

```

4. Run docker compose

```
docker compose -f docker-compose.yaml -f docker-compose.prod.yaml convert > cft-output.yaml
```

**Describe the results you received:**

The VPC that i mentioned in x-aws-vpc will not appear under  cft-output.yaml.  Instead the default VPC will appear here.

**Describe the results you expected:**

The specifics of the x-aws-vpc and the related subnets should appear in the output. However, x-aws-autoscaling indeed gets appended correctly. as expected.

**Output of `docker version`:**

```
docker-sample anshrma$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           ecs-us-east-1
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown

```

**Output of `docker context inspect`:**  

```
docker context inspect
[
    {
        "Name": "ecs-us-east-1",
        "Metadata": {
            "Description": "credentials read from environment",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "CredentialsFromEnv": true
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/anshrma/.docker/contexts/meta/2822874a6ac1b4b6839e6189a279e178d89a2d74a60af989dde59213cfa437c2",
            "TLSPath": "/Users/anshrma/.docker/contexts/tls/2822874a6ac1b4b6839e6189a279e178d89a2d74a60af989dde59213cfa437c2"
        }
    }
]

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):** 
AWS ECS
