### ISSUE TITLE
Expecting: LaunchType: EC2, Got: LaunchType: Fargate

### ISSUE THREAD

**Issue by jolson629** [docker/compose-cli#1284]
**Description**

Expecting LaunchType: EC2, Got: LaunchType: Fargate

**Steps to reproduce the issue:**
1. The following produces LaunchType: EC2:

```
services:
 test:
    image: "image"
    deploy:
      placement:
        constraints:
          - "node.ami == ami123456789"
          - "node.machine == t0.femto"
      resources:
        # devices:
        #   - capabilities: ["gpu"]
        reservations:
          memory: 8Gb
          generic_resources:
            - discrete_resource_spec:
                kind: gpus
                value: 1
```

```
ubuntu@dev01r01:~/project/docker$ docker compose convert |grep LaunchType
      LaunchType: EC2
```

2. Adding a bind mount causes the unexpected error "ECS Fargate does not support bind mounts from host: incompatible attribute":

```
services:
 test:
    image: "image"
    volumes:                                            <--------------------------------
       - ../blah/blah.conf:/etc/blah.conf
    deploy:
      placement:
        constraints:
          - "node.ami == ami123456789"
          - "node.machine == t0.femto"
      resources:
        # devices:
        #   - capabilities: ["gpu"]
        reservations:
          memory: 8Gb
          generic_resources:
            - discrete_resource_spec:
                kind: gpus
                value: 1
```

```
ubuntu@dev01r01:~/project/docker$ docker compose convert |grep LaunchType
      ECS Fargate does not support bind mounts from host: incompatible attribute
```

**Describe the results you received:**

See above!

**Describe the results you expected:**

Expecting to get a working CF script that used a LaunchType of EC2 and no error.

**Additional information you deem important (e.g. issue happens only occasionally):**

100% reproducible.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           myecscontext
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "testecscontext",
        "Metadata": {
            "Description": "(us-east-1)",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Profile": "default"
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/home/ubuntu/.docker/contexts/meta/8bb20fb47c424874f61b3bdfeb471eaddba",
            "TLSPath": "/home/ubuntu/.docker/contexts/tls/8bb20fb47c4248914f61b3bdfeb471eaddba"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-41-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.837GiB
 Name: net-per01
 ID: 
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
