### ISSUE TITLE
Support ephemeral host ports in ECS

### ISSUE THREAD

**Issue by SamuelMS** [docker/compose-cli#1314]
**Description**

It's currently impossible to set dynamic / ephemeral ports for a container:host binding, i.e. `80:0`, which is unfortunate since it's otherwise challenging to run multiple instances of the same task on any given host.

Compose also entirely ignores the `published` property of long-format ports:

```yaml
ports:
  - target: 80
    published: 0
```

Which generates:

```yaml
PortMappings:
  - ContainerPort: 80
    HostPort: 80
```

Clearly, this isn't what we intended.

The only solution at this point is to copy the _entire_ `ContainerDefinitions` array from `docker compose convert` into a CloudFormation overlay and replace the `PortMappings` list with the ephemeral port (0) – which completely defeats the point of the tool.

**Steps to reproduce the issue:**
1. Create a new compose file and add CloudFormation overlays for bridge networking.
2. Attempt to use an ephemeral port in your host binding (i.e. `0:80` or via long format).
3. View the incorrect configuration in `docker compose convert`.

**Describe the results you received:**

CloudFormation overlays allow users to customize bits of their ECS stack that aren't specific to compose – i.e. autoscaling, cluster capacity strategies, etc. We use overlays to indicate that we want to use EC2-backed containers, not Fargate ones. If we only run one task per host, this is all of the task-specific config that we require:

```yaml
ApiTaskDefinition:
  Properties:
    NetworkMode: "bridge"
    RequiresCompatibilities:
      - EC2
```

However, since `PortMappings` aren't generated properly, this is the config we have to use instead:

```yaml
ApiTaskDefinition:
  Properties:
    NetworkMode: "bridge"
    RequiresCompatibilities:
      - EC2
      # it's incredibly unfortunate that we have to manually define ContainerDefinitions here, but it's the only way
      # to set an ephemeral port on the host (0) so tasks can run concurrently
    ContainerDefinitions:
      - Command:
          - '<snip>'
        Essential: false
        Image: docker/ecs-secrets-sidecar:1.0
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: <snip>
        MountPoints:
          - ContainerPath: /run/secrets/
            SourceVolume: secrets
        Name: Api_Secrets_InitContainer
        Secrets:
          - <large list of secrets>
      - Command:
          - us-west-2.compute.internal
          - <snip>
        Essential: false
        Image: docker/ecs-searchdomain-sidecar:1.0
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: <snip>
        Name: Api_ResolvConf_InitContainer
      - Command:
          - /start
        DependsOn:
          - Condition: SUCCESS
            ContainerName: Api_Secrets_InitContainer
          - Condition: SUCCESS
            ContainerName: Api_ResolvConf_InitContainer
        Environment:
          - <large list of environment keys>
        Essential: true
        Image: <snip>
        LinuxParameters: { }
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: <snip>
        MountPoints:
          - ContainerPath: /run/secrets/
            ReadOnly: true
            SourceVolume: secrets
        Name: api
        PortMappings:
          - ContainerPort: 5000
            HostPort: 0
        RepositoryCredentials:
          CredentialsParameter: <snip>
```

99% of the above definition is auto-generated by `docker compose` – but since we need to override `PortMappings`, and `ContainerDefinitions` is a list type that doesn't support merging, we have to inline the _entire_ definition. It works, but it's awful and hard to maintain.

**Describe the results you expected:**

Setting `0:80` for port should generate the following port mapping:

```yaml
PortMappings:
  - ContainerPort: 80
    HostPort: 0
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           obsesh
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "<snip>",
        "Metadata": {
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Profile": "<snip>"
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "<snip>",
            "TLSPath": "<snip>"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 75
  Running: 2
  Paused: 0
  Stopped: 73
 Images: 1646
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.778GiB
 Name: docker-desktop
 ID: JUZV:M5TQ:Y7YZ:OZQB:6JHZ:XUIU:VEIK:IC5T:HCB7:MGP7:YH5B:OWSB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 60
  Goroutines: 63
  System Time: 2021-02-16T18:14:35.535272Z
  EventsListeners: 5
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

AWS ECS

**Comment by ndeloof** [comment]
I'll need to double check use of `PortMappings` with awsvpc, and especially if service-to-service communication is possible using the published port. If this works well, then we can add support for this in ECS integration

**Comment by SamuelMS** [comment]
@ndeloof `PortMappings` is generated for both our Fargate tasks and our EC2 tasks, but for the latter case we use CloudFormation overlays to switch the network mode to `bridge` to enable dynamic port bindings on a host. This all works remarkably well – the services all come online and private DNS resolution is fine – but the ephemeral port `0` was being ignored so sister tasks failed to spawn.

**Comment by ndeloof** [comment]
ok. ECS integration focus on Fargate deployment and awsvpc, so you're setup is a significant divergence from our target model. If this option can't be supported in a generic way, we don't want to enable it as this would just let others shoot into their own foot.

**Comment by SamuelMS** [comment]
@ndeloof Maybe, but the docs have tons of overloads for AWS-specific features (`x-aws-policies`, x-aws-loadbalancer`, etc). There's even a compose override for ports themselves (so AWS generates an ALB instead of an NLB):

```yaml
services:
  test:
    image: nginx
    ports:
      - target: 8080
        x-aws-protocol: http
```

https://docs.docker.com/cloud/ecs-compose-examples

So I'd say that this has pretty solid first-party support.

Anyway, the problem here doesn't have much to do with the networking mode, or even the container backing, but just that the host port part of the binding (`published`) is flat-out ignored for non-obvious reasons. If we can fix that, I wouldn't need to do anything with the CloudFormation overlays and life gets easier.
