### ISSUE TITLE
.env takes precedence over shell variables

### ISSUE THREAD

**Issue by briggySmalls** [docker/compose-cli#1327]
Hello! very grateful for the existence of this tool! However got a bit confused by the following behaviour

When a `.env` file is present, these variables take precedence over those defined in the shell.

This deviates from the [`docker-compose` behaviour](https://docs.docker.com/compose/environment-variables/#the-env-file) which surprised me.

**Steps to reproduce the issue:**
1. Create a simple `docker-compose.yml` as below:
```yaml
# docker-compose.yaml
services:
  web:
    image: ubuntu
    environment:
      TEST: "$FROM_ENV"
```
2. Create a `.env` file which defines the variable
```ini
# .env
FROM_ENV=".env"
```
3. Execute a compose command whilst also supplying a variable, observe how `.env` file wins:
```
/src $ env FROM_ENV="shell" docker compose convert
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
name: src
workingdir: /src
services:
  web:
    environment:
      TEST: .env
    image: ubuntu
    networks:
      default: null
networks:
  default:
    name: default
composefiles:
- /src/docker-compose.yml
```
4. Compare that with `docker-compose`, where the shell assignment wins:
```
/src $ env FROM_ENV="shell" docker-compose config
services:
  web:
    environment:
      TEST: shell
    image: ubuntu
version: '3.9'
```

**Describe the results you received:**

Environment variables set in a `.env` take precidence.

**Describe the results you expected:**

Environment variable defined in the shell to take precedence, like with `docker-compose`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 213
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 8.751GiB
 Name: docker-desktop
 ID: H5VK:36AS:UOHX:KXTT:WSRY:ADEC:YONS:EPO4:2Q5F:RKS7:QKU7:OFSN
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 76
  Goroutines: 92
  System Time: 2021-02-19T16:49:28.1815841Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
