### ISSUE TITLE
[Proposal] Add additional logic in docker compose to adapt EFS access to non-root users 

### ISSUE THREAD

**Issue by mreferre** [docker/compose-cli#1459]
This is to report both a product and a documentation enhancement.

I am trying to deploy [this docker compose file](https://github.com/ome/docker-example-omero/blob/master/docker-compose.yml) to Amazon ECS and I am not able to deploy it “as-is”. 

The `omero-server` container keeps dying due to a permission denied when reading/writing the volume. This is because the `omero-server` container uses a non-root user id (`1000:997`). The compose/ECS integration creates an EFS volume and an EFS Access Point on the root directory (`/`) that only allows the `root` user to read from / write to. The [docker docs that talks about the volumes](https://docs.docker.com/cloud/ecs-integration/#volumes) hint about this and they suggest you could use a specific user to match the POSIX configuration of the file system. This user is basically used to mask the user of the incoming request. In fact, one way to make it work would be to set the mask to use `0:0` (the root user) in the compose file like this:    

```
  omero:
    driver_opts:
      # Access point configuration
      uid: 0
      gid: 0
```
This, behind the scenes, converts to the following CFN code:

```
  OmeroAccessPoint:
    Properties:
      AccessPointTags:
      - Key: com.docker.compose.project
        Value: docker-example-omero
      - Key: com.docker.compose.volume
        Value: omero
      - Key: Name
        Value: docker-example-omero_omero
      FileSystemId: fs-7cb2e17b
      PosixUser:
        Gid: "0"
        Uid: "0"
    Type: AWS::EFS::AccessPoint
```

Another alternative to make this work would be to set a distinct `root_directory` as the Access Point owned by a random user (e.g. 10000:10000) and setting the mask to this same random user. Like this:  

```
  omero:
    driver_opts:
      # Access point configuration
      uid: 10000
      gid: 10000
      root_directory: “/omero” 
      permissions: 777
```

This converts to the following CFN code:

```
  OmeroAccessPoint:
    Properties:
      AccessPointTags:
      - Key: com.docker.compose.project
        Value: docker-example-omero
      - Key: com.docker.compose.volume
        Value: omero
      - Key: Name
        Value: docker-example-omero_omero
      FileSystemId:
        Ref: OmeroFilesystem
      PosixUser:
        Gid: "10000"
        Uid: "10000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "10000"
          OwnerUid: "10000"
          Permissions: "777"
        Path: /omero
    Type: AWS::EFS::AccessPoint
```
This is basically saying EFS to create a fs, create a folder owned by `10000` with permissions 777, create an AP on that folder and finally masking all requests as user `10000`. The documentation doesn't seem to include this example and it would be nice to update the docs to include the syntax for specifying `root_directory` and `permissions` (in addition to just add user/group). 

Both these two solutions work but they are not ideal because I’d need to tweak the compose to make it work (I would love the compose command to use good judgement and make sensible choices for me instead). 

I am wondering if we could embed logic into the docker binary itself so that it is possible, in the case I am creating a volume to be consumed by a container with a non-root user, to make it work without asking the user to tweak their existing compose file. 

The Access Point directory could be a random name picked by docker compose or it could be the name of the directory the container would want to mount it to (but not sure if we want to go down the rat-hole of having to deal with nested directories e.g. `/my/mount/point`).
