### ISSUE TITLE
Docker-ECS load balancer, HTTPS and routing

### ISSUE THREAD

**Issue by MartinJ-Dev** [docker/compose-cli#1472]
Greetings! This issue has been discussed a lot elsewhere. After reading all the docs and other related issues, we still aren’t sure how to do it. We are hoping to get concrete guidance for setting up our stack which can be conceptualized in the following way

```
services:
  # UI - single page app using Vue.js. It calls API gateway for any backend services
  frontend:
    image: ${IMG_FRONTEND}
    ports:
      - 80:80
      - 443:443

  # API gateway using Gunicorn. It handles auth and forwards requests to internal services
  api:
    image: ${IMG_API}
    ports:
      - 8000:8000

  # Internal service only accessible from API gateway and other internal services
  svc1:
    image: ${IMG_SVC1}
    expose:
      - 8000

  # Same as svc1
  svc2:
    image: ${IMG_SVC2}
    expose:
      - 8000
```

How do we set up the compose so that:
- All external traffics secured by HTTPS
- Requests can be correctly routed to frontend and API gateway
- Redirect 80 to 443 
- Ideally everything done in compose and no need to mess with CloudFormation

------------------

While this can be easily achieved using Traefik but we struggle with Docker-ECS. So far we understand:
- No path routing so we can’t route UI request to `example.com` and API requests to `api.example.com` 
- Port mapping has to be the same 

We are particularly confused because the official doc is limited but community resource with examples contain conflictive information. 

For example, the doc says 

```
Setting SSL termination by Load Balancer

x-aws-cloudformation:
  Resources:
    WebappTCP80Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:certificate/123abc"
        Protocol: HTTPS
```

Looks simple but then the community suggests otherwise. 

https://techsparx.com/software-development/docker/docker-ecs/load-balancer/https.html

Slack groups also confirms there no way to avoid going through this. 

We understand this project is still in development with its limitation so we are flexible in terms of technical solutions as long as business requirements are satisfied. Any feedback is appreciated.

**Comment by MartinJ-Dev** [comment]
Related issues:
https://github.com/docker/compose-cli/issues/775
https://github.com/docker/compose-cli/issues/777
https://github.com/docker/compose-cli/issues/1426
https://github.com/docker/compose-cli/issues/703
https://github.com/docker/compose-cli/pull/871

**Comment by ndeloof** [comment]
Hi. 

> While this can be easily achieved using Traffik but we struggle with Docker-ECS. 

This is indeed the main issue to address this: we don't want to provide yet another set of AWS-specific extensions that won't ever be adopted in the compose-spec. But on the other hand, compose model doesn't cover the "routing" aspect, so this need to be defined in a portable way. We also need to offer a transparent support for local development, maybe using a simplistic approach like we do for secrets, by just bind mounting plain text files.

A viable solution will require
- a high-level, declarative approach in compose model
- embed Træffik (or comparable) on `compose up` for local development
- map this to AWS resources and infrastructure

In the meantime, there's no simple option with ECS integration but to tweak the CloudFormation template to "fill the gap"

**Comment by MartinJ-Dev** [comment]
@ndeloof Thanks for getting back. We are happy to adopt any alternatives. Can you elaborate on your viable solution, specifically "a high-level, declarative approach" and "map to AWS"?

Since we can't do path routing, we are considering the following approach:
- Use Docker-ECS as pure backend API services with the gateway as a single entry point connected to ALB. 
- Host frontend somewhere else (S3 or comparable) 
- Local development will have `compose up` for the backend and run frontend locally or in another container. 

Would something like this work? If so, would setting up HTTPS be as simple as in the doc?

**Comment by ndeloof** [comment]
I'm only thinking "middle/long terms". There's no silver-bullet solution to this yet, but to create your own Load balancer and tweak the generated CloudFormation template for your needs.

**Comment by MartinJ-Dev** [comment]
@ndeloof Any feedback? Today we try to setup HTTPS for load balancer using the example in doc

```
version: '3.8'

services:
  proxy:
    image: nginx
    ports:
      - "80:80"

x-aws-cloudformation:
  Resources:
    ProxyTCP80Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:us-west-2:xxxx:certificate/xxxx"
        Protocol: HTTPS
```

The certificate is a valid one from ACM. We point our domain DNS CNAME to the DNS name of load balancer created by compose `xxxx.us-west-2.elb.amazonaws.com`. Unfortunately it can't be reached. Please advise.

**Comment by ndeloof** [comment]
double check you access your service on port 80, which is not the default one for https:
https://xxxx.us-west-2.elb.amazonaws.com:80/

**Comment by MartinJ-Dev** [comment]
`https://xxxx.us-west-2.elb.amazonaws.com:80/` gives "Not secure" warning in Chrome. I assumed this is because certificate is tied to a domain name. Following that information, we updated our certificate and DNS CNAME. Now we can successfully access `https://www.domain.com:80`

While this is encouraging, how do we access this domain on HTTPS without `:80`? In production, we can't have clients visit us by attaching a port number.

**Comment by ndeloof** [comment]
we don't yet have an option to expose a distinct port for ingress traffic. You can tweak the cloudformation template so it set Listener external port to 443, or can change your compose file so that port 443 is used for service's HTTP traffic

**Comment by al-dpopowich** [comment]
Another option which I have used is adding a nginx container, which is the only container with published ports, 80 and 443.  Then I use nginx for all internal routing.  You can put your cert and private key in secrets and configure your nginx container to use those files mounted at `/run/secrets/{certificate,private_key}`.  Added bonus: your SPA doesn't have to be configured to use a different host/port and just references, say, `/api/...` on the origin host.  Another bonus: there's virtually no difference between my development environment and production environment.

**Comment by Rovel** [comment]
@al-dpopowich can you share the compose file you are using to load nginx conf and ssl stuff, I tried to replicate you tip using something like this, but I get the error `ECS Fargate does not support bind mounts from host: incompatible attribute`, How do I access/map theses secrets to NGINX default folders?
thanks
```yaml
version: '3.7'

services:

  blog:
    image: my_blog:latest
    restart: always
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - ssl_certificate
      - private_key
    volumes:
      - /run/secrets/{nginx_conf}:/etc/nginx/conf.d
      - /run/secrets/{ssl_certificate,private_key}:/etc/nginx/ssl
secrets:
  ssl_certificate:
    name: "arn:aws:secretsmanager:my-region-1:account_id:secret:ssl_certificate-ABCDE"
    external: true
  private_key:
    name: "arn:aws:secretsmanager:my-region-1:account_id:secret:private_key-ABCDE"
    external: true
  nginx_conf:
    name: "arn:aws:secretsmanager:my-region-1:account_id:secret:nginx-conf-ABCDE"
    external: true
```

` WARNING services.restart: unsupported attribute  ECS Fargate does not support bind mounts from host: incompatible attribute`
