### ISSUE TITLE
Not possible to pull secret when existing LB is used

### ISSUE THREAD

**Issue by rosven** [docker/compose-cli#1510]
I assume the loadbalancer should have little to nothing to do with the permissions for the deployment flow regarding pulling secrets from AWS secret manager or other resources? However when adding `x-aws-loadbalancer` to the config. Its not possible to resolve the secret anymore.. 🤷 

This configuration works for getting my secret from AWS secret manager
```
version: "3.0"
services:
  app:
    image: ECRImage
    ports:
      - 8080:8080
    secrets:
      - myDirtyLittleSecret

secrets:
  myDirtyLittleSecret:
    name: "secretArn"
    external: true
```

Adding my own loadbalancer, creates an error when resolving the secret in the secret manager.
```
version: "3.0"
x-aws-loadbalancer: "loadbalancerArn"
services:
  app:
    image: ECRImage
    ports:
      - 8080:8080
    secrets:
      - myDirtyLittleSecret

secrets:
  myDirtyLittleSecret:
    name: "secretArn"
    external: true
```

Output:
```
TaskFailedToStart: ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 1 time(s): failed to fetch secret arn:aws:secretsmanager:eu-west-1:123456789...
```

Am I doing something wrong here? 🤔

**Comment by rosven** [comment]
Strangely enough I am revisiting this error in another area :)

```
BatcloudService TaskFailedToStart: ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 5 time(s): failed to fetch secret arn:aws:secretsmanager:eu-west-1:123456789...
make[1]: *** [deploy-dev] Error 1
gmake: *** [Makefile:214: deploy-batcloud-dev] Error 2
```

getting this error when trying to override the fargate instance to not expose a public IP by doing this in the overlay:
```
    myService:
      Type: AWS::ECS::Service
      Properties: 
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
```
