### ISSUE TITLE
`compose config --profiles` does not list profiles

### ISSUE THREAD

**Issue by aiordache** [docker/compose-cli#1519]
```yaml
[example]$ cat docker-compose.yml 
services:
  frontend:
    image: nginx
    profiles: 
      - test
  backend:
    image: nginx
```
```
[example]$ docker-compose config --profiles
test
```
```
[example]$ docker compose config --profiles
[example]$ 
```

Docs to be updated: https://github.com/docker/dev-tooling-team/issues/287
