### ISSUE TITLE
Race with depends_on and service_completed_successfully

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#1542]
**Description**

There appears to be a race when doing this:

```yaml
services:
  foo:
    image: alpine
    command: "echo hello"

  bar:
    image: alpine
    command: "echo world"
    depends_on:
      foo:
        condition: "service_completed_successfully"

```

`bar` never starts as `foo` runs and exits too quickly.

Adding a `sleep 1s` before the `echo hello` works around this.

**Steps to reproduce the issue:**
1. `docker compose up` the above

**Describe the results you received:**

`service_completed_successfully` shouldn't be timing dependent.

**Output of `docker version`:**

```
Cloud integration: 1.0.13-4-ga9c1f8fa
```
