### ISSUE TITLE
Support ulimits memlock for compatibility with docker-compose and elasticsearch images

### ISSUE THREAD

**Issue by jamshid** [docker/compose-cli#1558]
**Description**

It doesn't seem `docker compose` supports the `ulimits: memlock:` attribute like `docker-compose` does. This setting is used by the elasticsearch docker-compose.yml example.

These closed issues seem related but apparently not all `ulimits` were implemented?
https://github.com/docker/compose-cli/issues/1423
https://github.com/docker/compose-cli/issues/664

**Steps to reproduce the issue:**
1. Create the docker-compose.yml from https://www.elastic.co/guide/en/elasticsearch/reference/7.12/docker.html
```
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
```
2. `docker compose up`
3. See failure.
4. Ctrl-C and see no failure with `docker-compose up`.

**Describe the results you received:**
The memlock directive is ignored. 
```
    ulimits:
      memlock:
        soft: -1
        hard: -1
```

```
es01  | {"type": "server", "timestamp": "2021-04-15T21:59:20,869Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "es-docker-cluster", "node.name": "es01", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" }
es01  | ERROR: [1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
es01  | bootstrap check failure [1] of [1]: memory locking requested for elasticsearch process but memory is not locked
es01  | ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/es-docker-cluster.log
```
**Describe the results you expected:**

Expected docker-compose compatibility.

**Additional information you deem important (e.g. issue happens only occasionally):**

Since it's in this long-used example docker-compose.yml from Elastic it seems a good sign `memlock` support is needed.

**Output of `docker version`:**

```
20.10.5
```

**Output of `docker context show`:**  

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 33
  Running: 26
  Paused: 0
  Stopped: 7
 Images: 98
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: B3O2:PZ4U:FQCG:JUGW:45CQ:7MJA:V267:BYM6:CJCR:G3MT:XF2O:I5MO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Latest Docker for Desktop 3.3.0 on Mac Big Sur but also reproduced on latest Linux centos 7.9.2009
