### ISSUE TITLE
Merge the property: command

### ISSUE THREAD

**Issue by lagden** [docker/compose-cli#1601]
Docker version 20.10.5, build 55c4c88

`docker-compose.template.yml`
```yaml
version: "3.7"
services:
  app:
    image: debian
    command: >
      /bin/bash -c "
        echo 'template'
      "
```

`docker-compose.local.yml`
```yaml
version: "3.7"
services:
  app:
    image: alpine
    command: >
      /bin/ash -c "
        echo 'local'
      "
```

**Run**
```
docker compose -f docker-compose.template.yml -f docker-compose.local.yml up
```

**Expected**
```
Attaching to app_1
app_1  | local
app_1 exited with code 0
```

**Result**
```
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
```

---

Via old `docker-compose` works properly.
