### ISSUE TITLE
Additional labels syntax

### ISSUE THREAD

**Issue by avgas3** [docker/compose-cli#1617]
Currently, there are two working syntaxes for the labels: section of a service.

```yaml
labels:
  - traefik.enable=true
  - traefik.http.rotuers.gateway.rule=Host(`abc.mydomain.com`)
```
and 
```yaml
labels:
  - traefik.enable: "true"
  - traefik.http.rotuers.gateway.rule: Host(`abc.mydomain.com`)
```

What I think would be an excellent third option is:
```yaml
labels:
  traefik:
    enable: "true"
    http:
      routers:
        gateway:
          rule: Host(`abc.mydomain.com`)
