### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by rosven** [docker/compose-cli#1631]
Found some documentation/examples that aren't working as expected.

#### Issue 1
**Example:** https://docs.docker.com/cloud/ecs-compose-examples/
```
Autoscaling

Set a CPU percent target

services:
  foo:
    image: nginx
    deploy:
      x-aws-autoscaling: 75
```

not valid. `x-aws-autoscaling` cant be a number. Should be:

```
 deploy:
      x-aws-autoscaling: 
        cpu: 75
        max: 10
```

**error message:**
```
json: cannot unmarshal number into Go value of type ecs.autoscalingConfig
gmake: *** [Makefile:31: deploy-prod] Error 1
```

#### Issue 2
Example: https://docs.docker.com/cloud/ecs-compose-features/

```
Container Resources
CPU and memory limits can be set in compose. Those are used to select the minimal Fargate size that will match those limits.

services:
    nginx:
        image: mycompany/webapp
        deploy:
          resources:
            limits:
              cpu: 0.5
              memory: 2Gb
```

not valid. cpu should be a **string**. should be:

```
          resources:
            limits:
              cpu: '0.5'
              memory: 2Gb
```

**error message:**
```
* 'Deploy.Resources.Limits.cpus' expected type 'string', got unconvertible type 'int', value: '2'
gmake: *** [Makefile:31: deploy-prod] Error 1
```
