### ISSUE TITLE
npipe binding not created when running docker compose up

### ISSUE THREAD

**Issue by luke-barnett** [docker/compose-cli#1664]
**Description**

npipe bindings on windows are not created when running docker compose vs. directly running docker-compose.

**Steps to reproduce the issue:**
1. Create basic docker-compose.yaml definition using npipe binding
2. Run docker compose up
3. Inspect container to validate bindings are present

Example compose file:

```
version: "3.8"

services:

  traefik:
    image: traefik:v2.2.0-windowsservercore-1809
    command:
      - "--ping"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=npipe:////./pipe/docker_engine"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "8079:8080"
    volumes:
      - type: npipe
        source: '\\.\pipe\docker_engine_windows'
        target: '\\.\pipe\docker_engine'
```

**Describe the results you received:**
Container created without npipe binding

**Describe the results you expected:**
Container created with npipe binding

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:40 2021
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "npipe:////./pipe/docker_engine",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 9
  Running: 7
  Paused: 0
  Stopped: 2
 Images: 17
 Server Version: 20.10.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19042 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2009 (OS Build 19042.867)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.95GiB
 Name: SKYWALKER
 ID: ETWH:7FSL:CTRN:3CXS:JION:ESTD:OHXU:CNYN:UOTN:RXVU:4PWD:T7F4
 Docker Root Dir: E:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
