### ISSUE TITLE
Containers cant resolve other containers in the same docker compose network after Docker update v3.3.x

### ISSUE THREAD

**Issue by a7ul** [docker/compose-cli#1666]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 225A08E5-C48D-4E19-BE25-0BBAE8E9AD6B/20210422151048

### Expected behavior

Containers should be able to talk to each other in the same network using the docker compose network name.

### Actual behavior
```
database-setup_1  | psql: error: could not translate host name "db" to address: Name or service not known
```

### Information
 
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes after upgrading docker for mac from v3.2.x to v3.3.x
  - A reproducible case if this is a bug, Dockerfiles FTW. - See below.
 
  - macOS Version: BigSur 11.2.3
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior

The example below works with docker for mac v3.2.x 
If you upgrade to v3.3.x

You get the following error when `database-setup` container tries to connect to the postgres instance.

```
database-setup_1  | Ensuring database: postgres
database-setup_1  | psql: error: could not translate host name "db" to address: Name or service not known
```

Create a new repo with two files `docker-compose.yaml` and `initdbs.sh` with the following contents.

`docker-compose.yaml`

```yaml
version: "3.9"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      main:
        aliases:
          - db

  database-setup:
    image: postgres:12
    volumes:
      - ./initdbs.sh:/initdbs.sh
    depends_on:
      - postgres
    command: bash /initdbs.sh
    networks:
      main:
        aliases:
          - database-setup

networks:
  main:


```

`initdbs.sh`

```sh
#!/bin/bash
set -e

create_database () {
   echo "Ensuring database: $1"
   echo "SELECT 'CREATE DATABASE $1' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$1')\gexec" | psql postgres://postgres:secret@db
}


create_database postgres
create_database test1
create_database test2
create_database test3
create_database test4
create_database test5

```

Now run

```
 docker compose up
```

The following setup works in docker for mac v3.2.x but not in v3.3.x
Downgrading from 3.3.x solves the issue.

On v3.3.x

```
database-setup_1  | Ensuring database: postgres
database-setup_1  | psql: error: could not translate host name "db" to address: Name or service not known
```

After downgrading to 3.3.x

```
❯ docker-compose up --build
Recreating docker-repro_postgres_1 ... done
Recreating docker-repro_database-setup_1 ... done
Attaching to docker-repro_postgres_1, docker-repro_database-setup_1
database-setup_1  | Ensuring database: postgres
postgres_1        |
postgres_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1        |
postgres_1        | 2021-04-22 15:22:06.548 UTC [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1        | 2021-04-22 15:22:06.548 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1        | 2021-04-22 15:22:06.548 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1        | 2021-04-22 15:22:06.552 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1        | 2021-04-22 15:22:06.572 UTC [28] LOG:  database system was shut down at 2021-04-22 15:21:48 UTC
postgres_1        | 2021-04-22 15:22:06.577 UTC [1] LOG:  database system is ready to accept connections
database-setup_1  | Ensuring database: test1
database-setup_1  | CREATE DATABASE
database-setup_1  | Ensuring database: test2
database-setup_1  | CREATE DATABASE
database-setup_1  | Ensuring database: test3
database-setup_1  | CREATE DATABASE
database-setup_1  | Ensuring database: test4
database-setup_1  | CREATE DATABASE
database-setup_1  | Ensuring database: test5
database-setup_1  | CREATE DATABASE
docker-repro_database-setup_1 exited with code 0
```

**Comment by galxy25** [comment]
Also observing this issue after upgrading to docker 3.3.3 (64133) with compose 1.29.1

we use [docker-host](https://github.com/qoomon/docker-host/tree/v2.1.0) to keep the routing for the local version of our product as similar as possible to the remote environment.

Previously this docker-compose.yml config worked for allowing any other service running in the same network as the dockerhost service to resolve platform.local.tozny.com to the docker host IP 

```
  dockerhost:
    image: qoomon/docker-host:2
    cap_add: ["NET_ADMIN", "NET_RAW"]
    restart: always
    networks:
      default:
        aliases:
          - platform.local.tozny.com
          - docker-host
```

However now when doing `docker compose up` neither `platform.local.tozny.com` or `docker-host` resolve correctly 

We've been able to work around this by making the service name the actual DNS name
```
  platform.local.tozny.com:
    image: qoomon/docker-host:2
    cap_add: ["NET_ADMIN", "NET_RAW"]
    restart: always
    networks:
      default:
        aliases:
          - platform.local.tozny.com
          - docker-host
```
