### ISSUE TITLE
Docker compose does not respect COMPOSE_FILE variable in v1.0.14

### ISSUE THREAD

**Issue by tyronedd** [docker/compose-cli#1668]
**Description**

In version 1.0.14, when setting a list of files with the `COMPOSE_FILE` environment variable documented [here](https://docs.docker.com/compose/reference/envvars/#compose_file), it's not being used/respected.

**Steps to reproduce the issue:**

docker-compose.yml

```yml
version: "3.7"

services:
  db:
    image: postgres
    restart: always
```

docker-compose.ecs.yml

```yml
x-aws-cluster: not-a-actual-cluster-arn
```

minimal script:

```shell
# set environment variable
export COMPOSE_FILE="docker-compose.yml:docker-compose.ecs.yml"

docker compose config
```

**Describe the results you received:**

in v1.0.14:

```yml
services:
  db:
    image: postgres
    networks:
      default: null
    restart: always
networks:
  default:
    name: app_default
```

**Describe the results you expected:**

Like in version v1.0.13:

```yml
services:
  db:
    image: postgres
    networks:
      default: null
    restart: always
networks:
  default:
    name: app_default
x-aws-cluster: not-a-actual-cluster-arn
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:49 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 31
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-50-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.08GiB
 Name: tmeijn-NHxxRZQ
 ID: GAPM:YYBE:NYV5:F4NC:UTXI:A5WZ:VUG4:LEJZ:N3WA:DLXX:XVYR:5NB7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: tmeijn
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: 
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

local
