### ISSUE TITLE
ECS: docker labels are not supported

### ISSUE THREAD

**Issue by rverpillot** [docker/compose-cli#1706]
The compatibility table indicates that docker labels are supported in ECS, but this is not the case.
Neither at the container level, nor at the deployment level in docker compose file.

I get these warning messages:
```
WARNING services.labels: unsupported attribute       
WARNING services.labels: unsupported attribute       
WARNING services.deploy.labels: unsupported attribute       
```

**Comment by coobas** [comment]
Hi, I have exactly the same issue. Fully described in https://stackoverflow.com/questions/68692878/deploy-labels-in-docker-compose-not-supported-by-aws-ecs. 

Docker version: `Docker version 20.10.7, build f0df350`

Minimum compose file to reproduce:
```
version: "3"

services:
  proxy:
    image: traefik:v2.5
    deploy:
      labels:
        - traefik.enable=true
```

Ouput:
```
WARNING services.deploy.labels: unsupported attribute
```
