### ISSUE TITLE
Q: Installation script returns curl: no URL specified!

### ISSUE THREAD

**Issue by Feelixe-tin** [docker/compose-cli#1737]
I have the following job set up on CircleCI. It worked yesterday but today I get the error below. Since it's a completely clean ubuntu instance I'm assuming there's something wrong with the installation script? 
```
machine:
  image: ubuntu-2004:202010-01
steps:
  - checkout
  - run:
    name: "Install Docker Compose CLI"
    command: |
      curl -L https://raw.githubusercontent.com/docker/compose-cli/v1.0.16/scripts/install/install_linux.sh | sh
```

```
#!/bin/bash -eo pipefail
curl -L https://raw.githubusercontent.com/docker/compose-cli/v1.0.16/scripts/install/install_linux.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6325  100  6325   Running checks...    0 --:--:-- --:--:-- --:--:--     0
100  6325  100  6325    0     0  39043      0 --:--:-- --:--:-- --:--:-- 38803
Checks passed!
Downloading CLI...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

Exited with code exit status 2
CircleCI received exit code 2
```
