### ISSUE TITLE
Unable to use existing EFS filesystem

### ISSUE THREAD

**Issue by jarrah42** [docker/compose-cli#1739]
**Description**

I'm trying to start a service using ECS and mount an existing EFS as a volume. When I try, I get the following error:

```
mount target already exists in this AZ (Service: AmazonElasticFileSystem; Status Code: 409; Error Code: MountTargetConflict; Request ID: ea894cad-f63e-4aeb-8e4f-7711a28102e3; Proxy: null)
```

**Steps to reproduce the issue:**
1. Create an EFS filesystem and put data in it.
2. Create an AWS context and use it.
3. Run 'docker compose up'

**docker-compose.yml**

```
version: '3'
services:
    coney-neo4j: 
      image: neo4j:3.5
      ports:
        - "127.0.0.1:7474:7474"
        - "127.0.0.1:7687:7687"
      volumes: 
        - coney-neo4j:/data
      networks:
        - coney-net      
networks:
  coney-net:
    driver: bridge

volumes:
  coney-neo4j:
    external: true
    name: fs-21bf435a
```

**Describe the results you received:**

```
mount target already exists in this AZ (Service: AmazonElasticFileSystem; Status Code: 409; Error Code: MountTargetConflict; Request ID: ea894cad-f63e-4aeb-8e4f-7711a28102e3; Proxy: null)
```

**Describe the results you expected:**

Filesystem to be mounted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           ryp
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
ryp
```

**Output of `docker info`:**

```
Command "info" not available in current context (ryp), you can use the "default" context to run this comman
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
