### ISSUE TITLE
ECS: don't expose all ports to load balancer

### ISSUE THREAD

**Issue by rverpillot** [docker/compose-cli#1740]
Sometimes we need to expose ports in ECS cluster, but not necessary to load balancer. For example, to use Cloudwatch prometheus agent in the ECS cluster we need to define tasks with exposed ports for getting metrics, but for security reasons, we don't want expose these ports to outside. But currently `compose` create a listener for each exposed port in the docker compose file.

So, a syntax like this might be useful:
```
services:
  test:
    image: myImage
    ports:
      - target: 3000
        x-aws-protocol: none
```
