### ISSUE TITLE
cloudformation template not being formed correctly

### ISSUE THREAD

**Issue by michaelbest55** [docker/compose-cli#1745]
**Description**

Hello, really cool to find this tool!
Here is my current situation, I'm trying to use this tool from within a gitlab ci/cd pipeline, which are running within docker containers. I've tested running my docker-compose from my local ubuntu machine, which correctly deploys my resources in ECS.
When I run this process in the gitlab docker image, it seems that the cloudformation template does not get created correctly. Am I doing something obviously wrong?
Thanks for your help :)

**Steps to reproduce the issue:**
.gitlab-ci.yml
```yaml
image: docker:latest

stages:
  - lint
  - build
  - deploy_aws

services:
  - name: docker:dind

lint-Dockerfile:
  stage: lint
  script:
    - docker run --rm -i hadolint/hadolint < Dockerfile
  rules:
    - changes:
      - Dockerfile

lint-python:
  stage: lint
  script:
    - docker run --rm -v $(pwd)/app:/apps alpine/flake8:3.9.2 /apps --exclude /apps/migrations/* --ignore=E402,F403,F405 --max-line-length=119
  rules:
    - changes:
      - /app


#TODO: add proper tagging, 
#TODO: add vault in separate stage to get aws password
build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u AWS -p "$AWS_PASSWORD" $AWS_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE --all-tags
    - docker tag $CI_REGISTRY_IMAGE:dev $AWS_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/aws_ci_example:dev
    - docker push $AWS_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/aws_ci_example --all-tags


deploy-dev:
  stage: deploy_aws
  script:
    - ln -s /usr/local/bin/docker /usr/local/bin/com.docker.cli
    - apk add --no-cache curl
    - mkdir /compose_cli
    - cd /compose_cli
    - curl -L --output /compose_cli/docker-linux-amd64.tar.gz  https://github.com/docker/compose-cli/releases/download/v1.0.16/docker-linux-amd64.tar.gz
    - tar xzf docker-linux-amd64.tar.gz; cd docker
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - ./docker context create ecs aws_ci_example --from-env
    - ./docker context use aws_ci_example
    - docker version
    - docker context inspect aws_ci_example
    - docker info
    - cat $ENV_FILE > $CODE_PATH/.env
    - ./docker-compose --debug compose -f $CODE_PATH/docker-compose-aws.yml convert
    - ./docker-compose --debug compose -f $CODE_PATH/docker-compose-aws.yml up
```

docker-compose-aws.yml
``` yaml
version: '3'

services:
  db:
    image: postgres:13.3
    env_file: .env
  ui:
    image: $AWS_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/aws_ci_example:dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env
    environment:
      - DEPLOYMENT=PRODUCTION
  redis:
    image: redis:6.2.4
  rq:
    image: $AWS_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/aws_ci_example:dev
    command: python worker.py
    env_file: .env
    environment:
      - DEPLOYMENT=QUEUE
    depends_on: 
      - ui
      - redis
      - db
 ```

```sh
Using docker image sha256:08bdaf2f88f90320cd3e92a469969efb1f066c6d318631f94e7864828abd7c75 for docker:latest with digest docker@sha256:585a68a58889914b8de7d94fad8ec1dbc06fef2be5db40dea8bc4f3350b6f71c ...
$ ln -s /usr/local/bin/docker /usr/local/bin/com.docker.cli
$ apk add --no-cache curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/4) Installing brotli-libs (1.0.9-r3)
(2/4) Installing nghttp2-libs (1.42.0-r1)
(3/4) Installing libcurl (7.77.0-r0)
(4/4) Installing curl (7.77.0-r0)
Executing busybox-1.32.1-r6.trigger
OK: 13 MiB in 24 packages
$ mkdir /compose_cli
$ cd /compose_cli
$ curl -L --output /compose_cli/docker-linux-amd64.tar.gz  https://github.com/docker/compose-cli/releases/download/v1.0.16/docker-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633  100   633    0     0   4615      0 --:--:-- --:--:-- --:--:--  4620
100 23.8M  100 23.8M    0     0  19.3M      0  0:00:01  0:00:01 --:--:-- 33.5M
$ tar xzf docker-linux-amd64.tar.gz; cd docker
$ export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
$ export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
$ export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
$ ./docker context create ecs [MASKED] --from-env
Successfully created ecs context "[MASKED]"
$ ./docker context use [MASKED]
[MASKED]
$ cat $ENV_FILE > $CODE_PATH/.env
$ ./docker-compose --debug compose -f  $CODE_PATH/docker-compose-aws.yml convert
services:
  db:
    environment:
      APP_SETTINGS: [MASKED]
      DATABASE_URL: [MASKED]
      POSTGRES_DB:[MASKED]
      POSTGRES_PASSWORD: [MASKED]
      POSTGRES_USER: [MASKED]
      REDISTOGO_URL: [MASKED]
      SECRET_KEY: [MASKED]
    env_file:
    - .env
    image: postgres:13.3
    networks:
      default: null
  redis:
    image: redis:6.2.4
    networks:
      default: null
  rq:
    command:
    - python
    - worker.py
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      ui:
        condition: service_started
    environment:
      APP_SETTINGS: [MASKED]
      DATABASE_URL: [MASKED]
      DEPLOYMENT: QUEUE
      POSTGRES_DB: [MASKED]
      POSTGRES_PASSWORD:[MASKED]
      POSTGRES_USER: [MASKED]
      REDISTOGO_URL: [MASKED]
      SECRET_KEY: [MASKED]
    env_file:
    - .env
    image: [MASKED].dkr.ecr.[MASKED].amazonaws.com/[MASKED]:dev
    networks:
      default: null
  ui:
    depends_on:
      db:
        condition: service_started
    environment:
      APP_SETTINGS: [MASKED]
      DATABASE_URL:[MASKED]
      DEPLOYMENT: PRODUCTION
      POSTGRES_DB: [MASKED]
      POSTGRES_PASSWORD: [MASKED]
      POSTGRES_USER: [MASKED]
      REDISTOGO_URL: [MASKED]
      SECRET_KEY: [MASKED]
    env_file:
    - .env
    image: [MASKED].dkr.ecr.[MASKED].amazonaws.com/[MASKED]:dev
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5000
      published: 5000
      protocol: tcp
networks:
  default:
    name: awsciexample_default
$ ./docker-compose --debug compose -f $CODE_PATH/docker-compose-aws.yml up
time="2021-06-06T19:59:38Z" level=debug msg="serving grpc connection"
time="2021-06-06T19:59:38Z" level=debug msg="stopping session"
time="2021-06-06T19:59:38Z" level=debug msg="serving grpc connection"
time="2021-06-06T19:59:38Z" level=debug msg="serving grpc connection"
time="2021-06-06T19:59:38Z" level=debug msg="serving grpc connection"
time="2021-06-06T19:59:38Z" level=debug msg="serving grpc connection"
#1 [rq internal] load build definition from Dockerfile
#1 sha256:ba9ffb5a35d5a213c9f134aa71d679e9dff32a538e25ecddab1a7ac3353d5d87
#1 transferring dockerfile: 84B 0.0s
#1 transferring dockerfile: 160B 0.2s done
#1 DONE 0.2s
#5 [ui internal] load .dockerignore
#5 sha256:6322840291eb9e2305725f0071f63656df80e8c8df57943e001fb3b81ef73bb6
#5 transferring context: 2B 0.0s done
#5 DONE 0.1s
#4 [ui internal] load build definition from Dockerfile
#4 sha256:3dc19d4c432f2efc7701b4c0237cdf0887f0e4b93fbe896f40e83d11ff246405
#4 transferring dockerfile: 160B 0.1s done
#4 DONE 0.1s
#2 [rq internal] load .dockerignore
#2 sha256:27de0cd6061ed6e18ac395ceafaf2fb93ece321c60f2e45d4426a5ca7402f17c
#2 transferring context: 2B 0.1s done
#2 DONE 0.1s
#7 [redis internal] load build definition from Dockerfile
#7 sha256:7b1725e542a5f6bdd16b16bd13dc675b21213dd5cc7049083605eea6cf558a55
#7 transferring dockerfile: 108B 0.1s done
#7 DONE 0.1s
#8 [redis internal] load .dockerignore
#8 sha256:8325950cb808b1cd24525668b1d3a16d04b2c088f844970c6ea606495f07186e
#8 transferring context: 2B 0.1s done
#8 DONE 0.1s
#6 [db internal] load .dockerignore
#6 sha256:0b2f64ef3733a0fac641cef6d10608c3adec3635d033c8be7625fd4ea18eaf51
#6 transferring context: 2B 0.1s done
#6 DONE 0.1s
#3 [db internal] load build definition from Dockerfile
#3 sha256:3e9116e140bb40d7c82f5b4fbbbcc869c79aaf835202cb3d80ae6b910e26c01e
#3 transferring dockerfile: 110B 0.1s done
#3 DONE 0.1s
#11 [redis internal] load metadata for docker.io/library/redis:6.2.4
#11 sha256:4e054acf07e19a4be424f566cc2ff2994b6725ce09e6faf1a9ee35b31dac78a1
time="2021-06-06T19:59:39Z" level=debug msg="stopping session"
time="2021-06-06T19:59:39Z" level=debug msg="stopping session"
time="2021-06-06T19:59:39Z" level=debug msg="stopping session"
time="2021-06-06T19:59:39Z" level=debug msg="stopping session"
#11 CANCELED
#10 [db internal] load metadata for docker.io/library/postgres:13.3
#10 sha256:f76e6331072015efd1f73b48105533773e0522fcc9e8303803365fa1af14af02
#10 CANCELED
#9 [ui internal] load metadata for [MASKED].dkr.ecr.[MASKED].amazonaws.com/[MASKED]:dev
#9 sha256:169aabe33c5680adddb1f6a7521795b6a436fa6ada73344f519534ccb9dbb688
#9 ERROR: unexpected status code [manifests dev]: 401 Unauthorized
------
 > [ui internal] load metadata for [MASKED].dkr.ecr.[MASKED].amazonaws.com/[MASKED]:dev:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests dev]: 401 Unauthorized
```

**Describe the results you received:**
As you can see, the output of the convert command does not give a proper cloudformation template.

**Describe the results you expected:**
A proper cloudformation template, I'm happy to provide the output from my local machine if this is helpful.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
$ docker version
Client:
 Cloud integration: 1.0.16
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:51:04 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:29 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.
```
$ docker context inspect [MASKED]
[
    {
        "Name": "[MASKED]",
        "Metadata": {
            "Description": "credentials read from environment",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "CredentialsFromEnv": true
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/root/.docker/contexts/meta/[HIDDEN]",
            "TLSPath": "/root/.docker/contexts/tls/[HIDDEN]"
        }
    }
]

```

**Output of `docker info`:**
```
$ docker info
Client:
 Context:    default
 Debug Mode: false
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.78-coreos
 Operating System: Alpine Linux v3.13 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.607GiB
 Name: 34dc3122b7b2
 ID: [MASKED]
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

It might be good to mention that the docker image that this is running in is not an ubuntu image.
