### ISSUE TITLE
The profile option is not being used

### ISSUE THREAD

**Issue by maxcnunes** [docker/compose-cli#1753]
**Description**

When a profile is passed to `docker compose` it is bringing  up all services instead of just those without a profile or with the provided profile:

**Steps to reproduce the issue:**
1. Create a docker-compose.yml file based on this content:
```yml
version: "3.9"
services:
  frontend:
    image: alpine:3.7
    command: sh -c 'echo "Started frontend" && sleep 999999'
    profiles:
      - frontend

  phpmyadmin:
    image: alpine:3.7
    command: sh -c 'echo "Started phpmyadmin" && sleep 999999'
    depends_on:
      - db
    profiles:
      - debug

  backend:
    image: alpine:3.7
    command: sh -c 'echo "Started backend" && sleep 999999'

  db:
    image: alpine:3.7
    command: sh -c 'echo "Started db" && sleep 999999'

```
2. Run `docker compose --profile debug up`

It brought up all services, including the frontend service which has a different profile:
<img width="1792" alt="Screen Shot 2021-06-07 at 14 51 13" src="https://user-images.githubusercontent.com/680356/121066470-50400600-c7a0-11eb-81f6-bc2319434569.png">

**Describe the results you expected:**

Should not bring up the frontend service because it has a different profile.

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  


```
default
```

**Output of `docker info`:**

```
Client:                                                                                                                                                                                                                                                [2/5]
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 443
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.7GiB
 Name: docker-desktop
 ID: MIHI:TVHS:QF6E:MSBL:KG2T:BTRS:4K37:3BD2:6JF2:YPTW:PHOG:6Y4P
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 471
  Goroutines: 2187
  System Time: 2021-06-07T17:58:56.55830695Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
