### ISSUE TITLE
`docker compose` incompatibility: error setting rlimit type 7: invalid argument: unknown

### ISSUE THREAD

**Issue by jamshid** [docker/compose-cli#1769]
**Description**

Using `ulimits` to set `nofile`, exactly as documented in https://docs.docker.com/compose/compose-file/compose-file-v3/#ulimits, causes a failure about `rlimit`.

**Steps to reproduce the issue:**
1. Just `docker compose up` this docker-compose.yml
```
# This fails with `docker compose up` but works with `docker-compose up`:
#    Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:446: setting rlimits for ready process caused: error setting rlimit type 7: invalid argument: unknown
#
services:
  whydoesthisfail:
    image: debian:10
    ulimits:
      nofile:
        soft: 32000
        hard: 40000
```
2. See failure:
```
% docker compose up
[+] Running 1/1
 ⠿ Container tmp_whydoesthisfail_1  Recreated                                                                                                              0.1s
Attaching to whydoesthisfail_1
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:446: setting rlimits for ready process caused: error setting rlimit type 7: invalid argument: unknown
```
3. It works fine with `docker-compose up`
```
% docker-compose up
Recreating tmp_whydoesthisfail_1 ... done
Attaching to tmp_whydoesthisfail_1
tmp_whydoesthisfail_1 exited with code 0
```

**Describe the results you received:**

above

**Describe the results you expected:**

same as with `docker-compose`

**Output of `docker version`:**

```
% docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          v1.19.7
  StackAPI:         Unknown
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
% docker context show
default

% docker context inspect default
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "kubernetes"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            },
            "kubernetes": {
                "Host": "https://kubernetes.docker.internal:6443",
                "SkipTLSVerify": false,
                "DefaultNamespace": "default"
            }
        },
        "TLSMaterial": {
            "kubernetes": [
                "ca.pem",
                "cert.pem",
                "key.pem"
            ]
        },
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 39
  Running: 39
  Paused: 0
  Stopped: 0
 Images: 64
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 13.67GiB
 Name: docker-desktop
 ID: 6QR7:AZHG:JVIG:SBPU:24NQ:X4K4:E5ND:E5TQ:ZVUO:4ZJE:KP5X:36ZF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Docker for Mac just upgraded to 3.4.0 I think it's a regression.

**Comment by jamshid** [comment]
WORKAROUND: the error seems to be caused by `soft` being smaller than `hard` so just set them equal.
```
services:
  whydoesthisfail:
    image: debian:10
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
```
