### ISSUE TITLE
ECS: Desired task count can be less than the minimum of the auto scaling rule.

### ISSUE THREAD

**Issue by parisk** [docker/compose-cli#1777]
**Description**

The desired task count can be less than the minimum of the auto scaling rule, if not set.

**Steps to reproduce the issue:**
1. Create a Docker Compose file with `deploy.x-aws-autoscaling`, but **NO** `deploy.replicas`
2. Set `deploy.x-aws-autoscaling.min` to a value bigger than `1` (e.g. `3`)
3. Convert to CloudFormation
4. Check that the desired count is less than the minimum of the autoscaling rule

**Describe the results you received:**

```yml
# ... truncated CloudFormation template
 WebService:
    DependsOn:
    - WebTCP80Listener
    Properties:
      Cluster: arn:aws:ecs:eu-central-1:523531285944:cluster/opap-api-ecs-canary
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      DesiredCount: 1

# ... truncated CloudFormation template

  WebScalableTarget:
    DependsOn:
    - WebService
    Properties:
      MaxCapacity: 100
      MinCapacity: 3

# ... truncated CloudFormation template
```

**Describe the results you expected:**
```yml
# ... truncated CloudFormation template
 WebService:
    DependsOn:
    - WebTCP80Listener
    Properties:
      Cluster: arn:aws:ecs:eu-central-1:523531285944:cluster/opap-api-ecs-canary
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      DesiredCount: 3

# ... truncated CloudFormation template

  WebScalableTarget:
    DependsOn:
    - WebService
    Properties:
      MaxCapacity: 100
      MinCapacity: 3

# ... truncated CloudFormation template
```

**Output of `docker version`:**

```
docker version
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
docker context inspect example
[
    {
        "Name": "example",
        "Metadata": {
            "Description": "credentials read from environment",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "CredentialsFromEnv": true
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/root/.docker/contexts/meta/4b1171705ef9872fcf504745036d44bfcbee2db43f63400ee41e7358bfd0e5a4",
            "TLSPath": "/root/.docker/contexts/tls/4b1171705ef9872fcf504745036d44bfcbee2db43f63400ee41e7358bfd0e5a4"
        }
    }
]
```

**Output of `docker info`:**

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
ECS

**Comment by ndeloof** [comment]
¯\\_(ツ)_/¯
Would you expect `compose up` to reject this misconfiguration?
Doesn't AWS autoscaling automatically updated the desired count applying the configured autoscaling policy?

**Comment by parisk** [comment]
TBH I would expect the output `DesiredCount` to be guarded between `MinCapacity` and `MaxCapacity`. Otherwise the output configuration is not valid. How do I know? I tried to edit the service in ECS and without changing anything it would not let me save it because of this.

**Why is this a problem though?**
With the following configuration I would always expect a minimum amount of 3 replicas. What I get is 1 replica, until the CPU threshold is hit.

```yml
deploy:
  x-aws-autoscaling:
    min: 3
    max: 100
    cpu: 60
```
