### ISSUE TITLE
docker compose does not handle --env-file variables when --file is in a subfolder (docker-compose does)

### ISSUE THREAD

**Issue by jj-meyer** [docker/compose-cli#1780]
**Description**
Variables declared using --env-file are not passed to a compose-file, if the compose-file is located in a subfolder of the project-directory.

```bash
$ docker compose version
    Docker Compose version 2.0.0-beta.3

$ docker-compose --version
    docker-compose version 1.29.2
```

**Steps to reproduce the issue:**
1. Create `./foo.yml` compose-file in the project-directory
```
services:
  nginx:
    build:
      context: .
      args:
        - FOO=${FOO}
    environment:
        - BAR=${BAR}
```

2. Copy `./foo.yml` to a `./subfolder/foo.yml` of the project-directory
```
services:
  nginx:
    build:
      context: .
      args:
        - FOO=${FOO}
    environment:
        - BAR=${BAR}
```

3. Create `./subfolder/foo.env` environment file
```
FOO="FOO_ENV"
BAR="BAR_ENV"
```
The Project folder should contain ...
```
./foo.yml
./subfolder/foo.yml
./subfolder/foo.env
```

**Describe the results you received:**
1. docker compose with `./subfolder/foo.yml` fails ❌
```
$ docker compose --project-directory . --env-file subfolder/foo.env --file subfolder/foo.yml config
```
❌   - FOO and BAR variables are not passed to `subfolder/foo.yml`
```
services:
  nginx:
    build:
      args:
        FOO: ""
    environment:
      BAR: ""
```

2. docker compose with `./foo.yml` in the project-directory succeeds ✅
```
$ docker compose --project-directory . --env-file subfolder/foo.env --file ./foo.yml config
```
3. docker compose with `./subfolder/foo.yml` and declared environment variables succeeds ✅
```
$ FOO="FOO_ENV" BAR="BAR_ENV"  docker compose --project-directory . --file subfolder/foo.yml config
```
4. `docker-compose` with `./subfolder/foo.yml` succeeds ✅
```
$ docker-compose --project-directory . --env-file subfolder/foo.env --file subfolder/foo.yml config
```
✅    - FOO and BAR variables are passed to `subfolder/foo.yml`
```
services:
  nginx:
    build:
      args:
        FOO: FOO_ENV
    environment:
      BAR: BAR_ENV
```
**Describe the results you expected:**
Variables declared using --env-file should be passed to a compose-file, if the compose-file is located in a subfolder of the project-directory. 

This works correctly when the compose-file is located in the project-directory, when the environment variables are declared and when `docker-compose` (Python version) is used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```bash
$ docker --version
    Docker version 20.10.7, build f0df350

$ docker compose version
    Docker Compose version 2.0.0-beta.3

$ docker-compose --version
    docker-compose version 1.29.2
```
**Output of `docker info`:**

```
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server Version: 20.10.7

Kernel Version: 5.10.25-linuxkit
Operating System: Docker Desktop
OSType: linux
Architecture: x86_64
```

Docker desktop for MacOS Intel : 3.4.0
