### ISSUE TITLE
Entrypoint logs not captured?

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1801]
Using 

```yaml
services:
        toto:
                image: alpine
                entrypoint: echo 
                command: "hello"
```

docker-compose show the expected "hello", while docker compose complete quietly
