### ISSUE TITLE
Reports `'compose' is not a docker command` in GitHub Actions environment

### ISSUE THREAD

**Issue by antoineco** [docker/compose-cli#1838]
**Description**

As of commit 98a781f5cfd02f4c06851d4f33031b496ef7d39b (current latest on `main`).

In the sandbox environment used by GitHub Actions (\*), the `compose` command isn't recognized, although the client reports `Cloud integration: 1.0.17`.

Full log corresponding to the reproductions scenario below: https://github.com/antoineco/docker-elk/pull/12/checks?check_run_id=2898689298

(\*) _a Ubuntu 20.04.2 VM running in Microsoft Azure_

**Steps to reproduce the issue:**
1. Create the following GitHub Actions workflow in `.github/workflows/compose-test.yaml`:

    ```yaml
    name: Compose V2 test

    on:
      push:
        branches: [ test-compose ]  # replace with branch name used to reproduce issue

    jobs:

      test-compose:

        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Prepare environment
            run: |
              # Enable support for Compose V2 (beta)
              #
              # Instructions:
              # https://github.com/docker/compose-cli/blob/main/INSTALL.md

              curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
              hash -r

              docker version
              docker compose version
    ```
2. Notice how the job fails with the error mentioned in the title, although the `docker version` step prints `Cloud integration: 1.0.17`.

**Describe the results you received:**

```
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Describe the results you expected:**

`docker compose` is a recognized command.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.6+azure
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c28948e3c12dce3d1df60b6f184990618553f
 Built:             Fri Apr  9 17:01:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6+azure
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd246c3ab53105434eef8ffe997b6fd14dc6
  Built:            Fri Apr  9 22:06:18 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6+azure
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., 0.5.1+azure)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.6+azure
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1033-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.791GiB
 Name: fv-az246-706
 ID: 2AHL:VS5Y:FHVP:G5QA:R65P:TYUO:TK4L:YHNR:YZAY:BOMQ:TCBV:H3Y2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: githubactions
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Azure VM managed by GitHub.

Full detail: https://github.com/actions/virtual-environments/blob/ubuntu20/20210614.1/images/linux/Ubuntu2004-README.md
