### ISSUE TITLE
ECS: Service discovery issue

### ISSUE THREAD

**Issue by orxelm** [docker/compose-cli#1851]
**Description**

Hi
Not sure if it's a bug or something i'm doing worng, but i have 2 services - app, ui.
On ECS when ui is replaced, all good. However, when app is updated, the ui is losing access to the service.

I will attach the compose.yml and the nginx.conf so it's easier to understand.
Tryied service discovery with both http://app:3000 and http://app.projectname.local:3000 and nothing.
At the minute that app is being replaced we lose access to the app.

docker-compose.yml
```
version: "3.8"
services:
  app:
    container_name: app
    image: 'app:latest'
    build: .

  ui:
    container_name: ui
    image: 'ui:latest'
    depends_on:
      - app
    build:
      context: ./nginx
    ports:
      - "443:443"

```

nginx.conf
```
events {}
http {
    server {

    	listen 443 ssl default_server;
    	listen [::]:443 ssl default_server;

    	root /usr/share/nginx/html;
    	index index.html index.htm index.nginx-debian.html;
    	include /etc/nginx/mime.types;

    	location /api{
            proxy_pass http://app.projectname.local:3000;
    	    proxy_set_header Host $host;
       	}

    	location / {
            try_files $uri $uri/ =404;
        }

    	# set client body size to 10M #
    	client_max_body_size 10M;
    }
}
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
