### ISSUE TITLE
Docker Desktop (Mac) now defaults to docker-compose 2.0.0-beta.4 which breaks things

### ISSUE THREAD

**Issue by davisford** [docker/compose-cli#1867]
**Description**

We upgraded our build server and the builds started failing.  We are using Docker Desktop 3.5.1 (Build 66090)

I realized after doing `docker-compose --version` and seeing it was now on a beta 2 version it might be the problem, so I changed our builds to use `docker-compose-v1` instead, and it resolves the problem.  The problem we saw was failure to create containers similar to this giant thread: https://github.com/moby/moby/issues/17960

Our builds always halted with `Error response from daemon: 404 page not found` when trying to create one of our containers in the compose file.   I tried everything in that github moby thread including deleting folders, uninstalling and re-installing, rebooting, etc. etc.  Nothing worked until I realized that it was the beta version of docker-compose that was the problem.  

Incidentally, I tried to turn on the flags `--verbose --log-level=DEBUG` to get more info, but compose 2-beta does not support the `--log-level` flag it seems?

```sh
$ docker-compose-v1 --version
docker-compose version 1.29.2, build 5becea4c
$ docker-compose --version
Docker Compose version 2.0.0-beta.4
```

**Steps to reproduce the issue:**
1.  Try docker-compose 2.0.0-beta.4 on a compose file with multiple containers, networks, volumes and see if it works?
2.  Revert back to v1 and see it work
3.

**Describe the results you received:**

Upgrading to the latest Docker Desktop broke builds because it uses beta 2 of docker-compose

**Describe the results you expected:**

The `docker-compose` binary shouldn't be switched to beta 2 version until all issues are resolved and it is stable.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.7, build f0df350
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
desktop-linux
```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.7GiB
 Name: docker-desktop
 ID: ZZAL:LPRH:T4PV:ZP2M:6G7Q:2QWM:7QGO:L2DQ:5J67:J3LS:XTZO:AN2S
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 67
  Goroutines: 109
  System Time: 2021-07-01T00:47:05.524205799Z
  EventsListeners: 5
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

macOS Catalina 10.15.7

**Comment by ndeloof** [comment]
I'd be happy to assist you if you can provide more details on the service configuration for the container that fails to be created (I assume other containers get successfully created in your compose file?).

By just telling us "2.0 breaks" make it clear about your frustration but don't give me any chance to fix potential bugs or improve diagnostic :P

**Comment by mat007** [comment]
> I changed our builds to use docker-compose-v1 instead, and it resolves the problem.

You can actually just go to the Settings in Docker Desktop and in the Experimental section there is a switch to toggle between legacy Compose (aka V1) and the new Compose (aka V2).

**Comment by davisford** [comment]
@mat007 why would they switch it to beta by default?  that seems completely wrong.  you should be able to go to experimental settings and switch it to v2 in the experimental settings if you want to try that, not the other way around.

**Comment by davisford** [comment]
@ndeloof Here is the compose file.  Unfortunately, it's not going to really be executable as it contains two of our private container builds.  However, if there's anything you see in the compose file that sticks out, let me know.

I scoured _all_ of the docker `host` and `vm` logs -- nothing really stuck out.  I _tried_ to enable verbose logging on compose with `--verbose --log-level=DEBUG` but compose v2 doesn't support that, so I couldn't get any additional info out of it.

I gave up trying to find the root cause once I realized `docker-compose-v1` works again, but I'm happy to try to provide any additional info I can.

```yaml
version: '3.5'
services:
  postgres:
    container_name: $DB_CONTAINER_NAME
    image: postgis/postgis
    hostname: postgres
    ports:
      # host : container
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posapi-test
  postgres-migrations:
    build: 
        context: ../db
    image: posapi-migrations:latest
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: posapi-test
      PGHOST: ${DB_CONTAINER_NAME}
      PGSSLMODE: disable
    command: ["/wait-for-postgres.sh", "/run-migrations.sh"]
  posapitests:
    build:
      context: ../
      dockerfile: jenkins.Dockerfile
    container_name: $TEST_CONTAINER_NAME
    image: api:tests
    environment: 
      # By here, db env is created and migrated, so we can use psql vars directly
      PGUSER: postgres
      PGHOST: ${DB_CONTAINER_NAME}
      AWS_REGION: us-east-1 # Has to match the region in the pos api config
      # SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - $BUILD_DIR:/tests
      # CRITICAL: Have to "share" the go module cache so that
      # the containers can reuse them and not try to download
      # the modules from remote sources.
      # Primarily, this is due to us using private repository
      # however it does have the added benefit of speeding up the container builds
      # as they don't have to request tons of stuff over network.
      - ${HOME}/go/pkg/mod/cache:/go/pkg/mod/cache
      # SSH_AUTH_SOCK doesn't work nicely on osx :( 
      # https://github.com/docker/for-mac/issues/483
      # - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    depends_on:
        - postgres-migrations
    command: ["/opt/pos-api/jenkins/run-tests.sh"]
  nats:
    container_name: nats
    image: nats:2.1.6
    ports:
      - 4222:4222
```
