### ISSUE TITLE
`docker-compose exec` stderr output goes to stdout

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1873]
**Description**

Use this docker-compose.yaml:

```yaml
services:
  web:
    container_name: web
    image: busybox
    user: "$UID:$GID"
    command: "tail -f /dev/null"
```

Now 

```bash
docker-compose exec -T web ls junker99
```

You'll see the expected `ls: junker99: No such file or directory` but unfortunately it's on stdout, not stderr, it should be on stderr (where the `ls` put it)

```bash
docker-compose exec -T web ls junker99 >/dev/null
````

shows no output, it should show `ls: junker99: No such file or directory`

docker-compose v1 does this correctly
