### ISSUE TITLE
`docker-compose config` behavior difference in volume naming between v1 and compose-cli

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1875]
**Description**

This is an obscure difference between docker-compose v1 and v2 (compose-cli), and I already solved it in ddev by using an explicit volume name, but I thought you might want to know about it.

Given this ssh.yaml:
```yaml
services:
  ddev-ssh-agent:
    image: busybox
    volumes:
    -  socket_dir:/tmp/.ssh-agent
volumes:
  socket_dir:
```

Given the command `docker-compose -f /Users/rfay/.ddev/ssh.yaml config`

In docker-compose v1, the result of the top-level volumes section is:

```yaml
volumes:
  socket_dir: {}
```

In compose-cli/docker-compose v2, the result of the top-level volumes section is:
```yaml
volumes:
  socket_dir:
    name: ddev_socket_dir
```

What difference does it make?

The v1 leaves the creation of the actual volume name to later (in ddev code), where the project name is provided. As a result, the created volume name is ddev-ssh-agent_socket_dir

In v2, the `name:` is make explicit in the `docker-compose conf` phase, so it takes the directory name (.ddev -> ddev) as the project name, meaning that the created volume name ends up being ddev_socket_dir.

This resulted in https://github.com/drud/ddev/issues/3075 which was pretty easily solved by https://github.com/drud/ddev/pull/3077, but I wanted to chase it and understand what was going on, since we talked about this in [slack](https://dockercommunity.slack.com/archives/G013121J9RN/p1625011415070700?thread_ts=1624995963.069500&cid=G013121J9RN).

It's a pretty obscure behavior change, with a pretty obscure result. But I suppose it could affect somebody else.
