### ISSUE TITLE
`docker compose` environment variables improperly casting while using defaults

### ISSUE THREAD

**Issue by emiliojc-dh** [docker/compose-cli#1903]
**Description**

When an environment variable has a default, the type is casted and the container fails to build with `<var> must be a string, number or null`

**Steps to reproduce the issue:**
1. Create new empty folder.
```sh
mkdir docker-env-default-issue && cd docker-env-default-issue
```
2. Create `foo.yml` file. Note that you can use `:-` or `-` as default.
```sh
echo 'services:\n  nginx:\n    build:\n      context: .\n    environment:\n        BAR: ${BAR-False}' > foo.yml
```
File contents:
```
services:
  nginx:
    build:
      context: .
    environment:
        BAR: ${BAR:-False}
```

**Describe the results you received:**
```
❯ docker compose --project-directory . --file foo.yml config
services.nginx.environment.BAR must be a string, number or null
```

You can easily check it works with something else with:
```
❯ BAR=foo docker compose --project-directory . --file foo.yml config
services:
  nginx:
    environment:
      BAR: foo
    networks:
      default: null
networks:
  default:
    name: docker-env-default-issue_default
```

**Describe the results you expected:**
```
❯ docker compose --project-directory . --file foo.yml config
services:
  nginx:
    environment:
      BAR: False
    networks:
      default: null
networks:
  default:
    name: docker-env-default-issue_default
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`: ***
```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
