### ISSUE TITLE
WARN[0000] The X variable is not set. Defaulting to a blank string

### ISSUE THREAD

**Issue by Tony-Sol** [docker/compose-cli#1907]
**Description**

Receive message 
```WARN[0000] The X variable is not set. Defaulting to a blank string.```
while run exec command for running container 

**Steps to reproduce the issue:**
Project structure:
docker-compose.yml content:
```
version: "3.8"
services:
    nginx:
        container_name: 'php-project-nginx'
        image: nginx
        env_file: .docker/.env
        ports:
            - ${PUBLISHED_NGINX_PORT}:8080
            - ${PUBLISHED_NGINX_PORT_SECURED}:443
        volumes:
            - ./:/var/www/app
            - ./.docker/nginx/cfg/etc/:/etc/nginx/
        depends_on:
            php:
                condition: service_healthy
    php:
        container_name: 'php-project-php-fpm'
        image: #
        working_dir: /var/www/app
        env_file: .docker/.env
        volumes:
            - ./:/var/www/app
            - ./.docker/php/cfg/etc/php/7.4/:/etc/php/7.4/
        healthcheck:
            test: [ "CMD", "php-fpm", "-t" ]
            interval: 3s
            timeout: 5s
            retries: 5
            start_period: 1s
    db:
        image: mysql:5.7
        container_name: 'php-project-mysql'
        env_file: .docker/.env
        ports:
            - ${PUBLISHED_MYSQL_PORT}:3306
        expose:
            - '3306'
        volumes:
            - project-db:/var/lib/mysql
    redis:
        image: redis:6.2
        container_name: 'php-project-redis'
volumes:
    project-db:
```
.docker/.env content:
```
PUBLISHED_NGINX_PORT=8082
PUBLISHED_NGINX_PORT_SECURED=433

MYSQL_DATABASE=db
MYSQL_USER=user
MYSQL_PASSWORD=password
MYSQL_ROOT_PASSWORD=password
MYSQL_HOST=db
MYSQL_PORT=3306

PUBLISHED_MYSQL_PORT=3308
```
.env content:
```
# APPLICATION
APP_ENV=prod
APP_NAME=php-project

# DATABASE
DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=5.7"
```

Directory structure:
```
.
├── .env // there are no vars, used in docker-compose.yml
├── .docker
│   ├── .env // file with vars used in docker-compose.yml
├── docker-compose.yml
```
1. zsh: `COMPOSE_PROJECT_NAME=project docker compose --env-file=.docker/.env up`
2. zsh: `COMPOSE_PROJECT_NAME=project docker-compose exec php bash`

**Describe the results you received:**
bash is running but get many warning messages about empty env:
```
tony@host ~/Projects/php-project$ COMPOSE_PROJECT_NAME=php-project docker compose exec php
WARN[0000] The PUBLISHED_NGINX_PORT variable is not set. Defaulting to a blank string. 
WARN[0000] The PUBLISHED_NGINX_PORT_SECURED variable is not set. Defaulting to a blank string. 
WARN[0000] The PUBLISHED_MYSQL_PORT variable is not set. Defaulting to a blank string. 
root@f0a22031d945:/var/www/app# 
```
but envs are in container:
```
printenv | grep -E "(*PUBLISHED_NGINX_PORT*|*PUBLISHED_MYSQL_PORT*)"
PUBLISHED_NGINX_PORT_SECURED=433
PUBLISHED_MYSQL_PORT=3308
PUBLISHED_NGINX_PORT=8082
```
**Describe the results you expected:**
No incorrect warning messages

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`: **
```
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
Docker version 20.10.7, build f0df350
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 4
  Paused: 0
  Stopped: 4
 Images: 14
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.807GiB
 Name: docker-desktop
 ID: A4XY:GZLQ:SKEX:3DS5:DURU:XV6W:52LE:RIW6:JIGI:TAJR:YGJL:BHGA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
`docker compose config` output:
```
tony@host ~/Projects/php-project$ COMPOSE_PROJECT_NAME=php-project docker compose --env-file=.docker/.env config
services:
  db:
    container_name: php-project-mysql
    environment:
      PUBLISHED_MYSQL_PORT: "3308"
      PUBLISHED_NGINX_PORT: "8082"
      PUBLISHED_NGINX_PORT_SECURED: "433"
    env_file:
    - .docker/.env
    expose:
    - "3306"
    image: mysql:5.7
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      published: 3308
      protocol: tcp
    volumes:
    - type: volume
      source: project-db
      target: /var/lib/mysql
      volume: {}
  nginx:
    container_name: php-project-nginx
    depends_on:
      php:
        condition: service_healthy
    environment:
      PUBLISHED_MYSQL_PORT: "3308"
      PUBLISHED_NGINX_PORT: "8082"
      PUBLISHED_NGINX_PORT_SECURED: "433"
    env_file:
    - .docker/.env
    image: nginx
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: 8082
      protocol: tcp
    - mode: ingress
      target: 443
      published: 433
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/tony/Projects/php-project
      target: /var/www/app
      bind:
        create_host_path: true
    - type: bind
      source: /Users/tony/Projects/php-project/.docker/nginx/cfg/etc
      target: /etc/nginx
      bind:
        create_host_path: true
  php:
    container_name: php-project-php-fpm
    environment:
      PUBLISHED_MYSQL_PORT: "3308"
      PUBLISHED_NGINX_PORT: "8082"
      PUBLISHED_NGINX_PORT_SECURED: "433"
    env_file:
    - .docker/.env
    healthcheck:
      test:
      - CMD
      - php-fpm
      - -t
      timeout: 5s
      interval: 3s
      retries: 5
      start_period: 1s
    image: #
    networks:
      default: null
    volumes:
    - type: bind
      source: /Users/tony/Projects/php-project
      target: /var/www/app
      bind:
        create_host_path: true
    - type: bind
      source: /Users/tony/Projects/php-project/.docker/php/cfg/etc/php/7.4
      target: /etc/php/7.4
      bind:
        create_host_path: true
    working_dir: /var/www/app
  redis:
    container_name: php-project-redis
    image: redis:6.2
    networks:
      default: null
networks:
  default:
    name: php-project_default
volumes:
  project-db:
    name: php-project_project-db
```
