### ISSUE TITLE
Hyphen isn't escaped in compose v2 env variables (block sequence entries are not allowed in this context)

### ISSUE THREAD

**Issue by quentincaffeino** [docker/compose-cli#1919]
#### .env:
```.env
SOME_VARIABLE="-"
```

#### docker-compose.yaml:
```yaml
services:
  svc:
    environment:
      OTHER_VARIABLE: ${SOME_VARIABLE}
```

Gives an error: `yaml: line 4: block sequence entries are not allowed in this context`

Of course solution would be to wrap `${SOME_VARIABLE}` in quotes but this used to work with previous composer so not sure if this is an issue. If not at least it might help someone searching for same problem.
