### ISSUE TITLE
v2.0.0-rc.1 regression: services.test.deploy.resources.limits.memory must be a string

### ISSUE THREAD

**Issue by jamshid** [docker/compose-cli#2014]
**Description**

Specifying memory as an env variable and in bytes causes `must be a string` error.

**Steps to reproduce the issue:**
1. Create this docker-compose.yml:
```
services:
  test:
    image: centos
    deploy:
      resources:
        limits:
          memory: "${MEM_LIMIT-1000000000}"
```
2. After enabling docker-compose V2:
```
% docker-compose --version
Docker Compose version v2.0.0-rc.1
```
3. Try to bring it up, both with the default or by setting MEM_LIMIT:
```
% docker-compose config          
services.test.deploy.resources.limits.memory must be a string

% MEM_LIMIT=2000000000 docker-compose config          
services.test.deploy.resources.limits.memory must be a string
```
4. After reverting to docker-compose 1.29 it works:
```
% docker-compose --version
docker-compose version 1.29.2, build 5becea4c

% docker-compose config                               
services:
  test:
    deploy:
      resources:
        limits:
          memory: '1000000000'
    image: centos
version: '3.9'

% MEM_LIMIT=2000000000 docker-compose config          
services:
  test:
    deploy:
      resources:
        limits:
          memory: '2000000000'
    image: centos
version: '3.9'
```
**Describe the results you received:**

False `must be a string` error with V2
**Describe the results you expected:**

V2 to work and to work like V1

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a regression from the previous release so I'm still unable to use V2

**Output of `docker-compose --version`:**

```
(paste your output here)
```

**Output of `docker version`:**

```
Docker Compose version v2.0.0-rc.1
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 39
  Running: 26
  Paused: 0
  Stopped: 13
 Images: 393
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: 73JY:7HGJ:KHL6:3VFW:XEAB:X3TO:WWG6:QFSP:LWJF:AJVH:CDBN:G663
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
M1 macOS 11.5.1

**Comment by mdantonio** [comment]
I found a similar problem with resources.reservations.cpus

with -beta6 this config was working:
```
services:
  myservice:
    image: alpine
    deploy:
      resources:
        reservations:
          cpus: 0.25
```

But now with rc1 it raises the error
```
* 'Deploy.Resources.Reservations.cpus' expected type 'string', got unconvertible type 'float64', value: '0.25'
```

In this case adding quotes is enough, but when variables are involved like:

```
services:
  myservice:
    image: alpine
    deploy:
      resources:
        reservations:
          cpus: ${MYCPUS}
```

double quotes are not enough and both double and single quotes are needed, in the docker-compose.yml OR in the .env
i.e.
`cpus: "'${MYCPUS}'"` (in docker-compose.yml)
or
`MYCPUS="'0.25'"`  (in .env)

Maybe @jamshid you could try the same trick as a workaround
