### ISSUE TITLE
Experimental Features bug: "$1" parsed out of .ENV variables in docker-compose

### ISSUE THREAD

**Issue by danbrellis** [docker/compose-cli#2015]
This is only a bug when Experimental Feature "Use Docker Compose V2" is *enabled*. Just an FYI.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E46B5445-8698-438D-8923-2652CF2F09EB/20210811153714

### Actual behavior
When docker pulls in my .env file (via docker-compose.yml) it parses out `$1` in the set variables.

### Expected behavior
Set the environment variables as presented in the .env file

### Information
  - Windows Version: 10.0.19042 Build 19042
  - Docker Desktop Version: 3.5.2
  - Docker Engine Version: v20.10.7
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

#### docker-compose.yml
```yml
version: '3.7'

services:
  # apache - web server with php
  apache:
    build:
      context: .
      network: host
    ports:
      - "8003:80"
    environment:
      APACHE_DOCUMENT_ROOT: "/var/www/web"
      CHOKIDAR_USEPOLLING: 1
    env_file:
      - ./.env
    volumes:
      - .:/var/www

```

#### .env
```.env
DB_PASSWORD=abcd$1efg
```

#### cmd.exe
```cmd
docker-compose up -d --build
```

#### index.php
```php
var_dump(getenv(DB_PASSWORD))
//string(7) "abcdefg"
```
