### ISSUE TITLE
Docker compose config fails with `invalid reference format` in ECS context when using .env variables

### ISSUE THREAD

**Issue by AttilaTheFun** [docker/compose-cli#2096]
I'm using the latest Docker Desktop and docker version:

```
docker --version
Docker version 20.10.8, build 3967b7d
```

I'm trying to deploy a compose application that runs fine locally to ECS.
I've simplified the compose files down to:

../docker-compose.yaml:
```
version: "3"
networks:
  app:
```

../../web/docker-compose.yaml:
```
version: "3"
services:
  web:
    container_name: web
    # image: 621687810286.dkr.ecr.us-west-1.amazonaws.com/web:latest
    image: ${DOCKER_REGISTRY}/web:latest
    networks:
      - app
```

And I have a .env file with:
```
DOCKER_REGISTRY=621687810286.dkr.ecr.us-west-1.amazonaws.com
```

When I run the following in the default context, it works:
```
% docker compose --env-file .env -f ../docker-compose.yaml -f ../../web/docker-compose.yaml config
services:
  web:
    container_name: web
    image: 621687810286.dkr.ecr.us-west-1.amazonaws.com/web:latest
    networks:
      app: null
networks:
  app:
    name: scripts_app
```

However, when I run the same thing with an ecs context I get this error:
```
% docker compose --env-file .env -f ../docker-compose.yaml -f ../../web/docker-compose.yaml config
invalid reference format
```

If I hardcode the docker registry string in the compose file rather than using a .env variable, the ecs context works.

Is something broken with the embedding of .env variables in the ECS implementation?
