### ISSUE TITLE
AWS ECS Fargate ARM64 support:

### ISSUE THREAD

**Issue by thorfi** [docker/compose-cli#2115]
Description

AWS have just announced support for ARM64 in Fargate:

https://aws.amazon.com/about-aws/whats-new/2021/11/aws-fargate-amazon-ecs-aws-graviton2-processors/

It would be good to have docker compose auto detect platform linux/arm64 and include CpuArchitecture: ARM64 chunk in the CloudFormation template, and also to have the docker/ecs-secrets-sidecar and docker/ecs-searchdomain-sidecar containers built as multi-platform images.

```
  Resources:
    FooTaskDefinition:
      Properties:
        RuntimePlatform:
          CpuArchitecture: ARM64
```
