### ISSUE TITLE
can't able to connect / communicate with folders in another container ?

### ISSUE THREAD

**Issue by testgithub-trial** [docker/compose-cli#2128]
I can't able to read the **template folder** from _frontend_ container.

## Here is my file structure.
![image](https://user-images.githubusercontent.com/88606059/151930481-212504be-d153-4d02-a6af-c98bf5f29c9d.png)
## Here is my docker-compose.yml 
```
version: '3.2'
services:
  frontend:
       build: ./frontend
       volumes:
        - ./home/doc-tryy-2/frontend:/var/lib/docker/volumes/doc-tryy-2_asset-volume1/_data
       

  backend:
      build: ./backend
      depends_on:
         - "frontend"
      ports:
         - "8080:8080"
      volumes:
        - ./home/doc-tryy-2/frontend:/var/lib/docker/volumes/doc-tryy-2_asset-volume1/_data
        
volumes:
  asset-volume1:

```  
## Here is my frontend/Dockerfile
```
FROM python:3.7-slim
WORKDIR /common_dir
ADD . /common_dir
COPY . ./
RUN pip3 install -r requirements.txt --user
```
## Here is my backend/Dockerfile
```
FROM python:3.7-slim
WORKDIR /common_dir
ADD . /common_dir
RUN pip3 install -r requirements.txt --user
EXPOSE 8080
CMD ["python3", "app.py"]

```
## Here is my backend/app.py
```
from flask import Flask, render_template, flash, redirect, url_for, session, logging, request

app = Flask(__name__)
app.secret_key = 'hello'

@app.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        uname = request.form["uname"]
        return render_template("loginpage.html", uname=uname)
    else:
        return render_template("loginpage.html")


if __name__ == "__main__":
    app.run(debug=True,port=8080,host='0.0.0.0')
```
## here is my _Error message_ i am getting
![image](https://user-images.githubusercontent.com/88606059/151932076-3691850c-8970-4e4f-93b1-6c3e40ca2f38.png)
