### ISSUE TITLE
Allows flexible setting of AssignPublicIp (Fargate)

### ISSUE THREAD

**Issue by nobiit** [docker/compose-cli#2135]
**Description**
I don't want clients to be able to directly access my service via public ip in any way. 

**Describe the results you received:**
Currently there is no way to disable flexible public ip

**Describe the results you expected:**
I expected to be able to set up assignPublicIP simply via ecs-compo.yml

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
https://github.com/docker/compose-cli/blob/main/ecs/cloudformation.go#L238-L245

**Comment by nobiit** [comment]
In the meantime, you can try
```
x-aws-cloudformation:
  Resources:
    <Service>Service:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
```
