### ISSUE TITLE
Unnecessary warnings when deploying with a ECS context: services.scale unsupported

### ISSUE THREAD

**Issue by chrisbecke** [docker/compose-cli#2142]

**Comment by ssensalo** [comment]
Hi @JohnPreston 
Your response is helpful, currently, I am able to mount the EFS volume but the container keeps failing. This is how I have written my `docker-compose.yaml` 
```
version: "2"
services:
  lawuna_server:
    environment:
          DB_USER = ["DB_USER"]
          DB_PASSWORD = ["DB_PASSWORD"]
          DB_HOST = ["DB_HOST"]
          DB_PORT = ["DB_PORT"]
          DB_NAME = ["DB_NAME"]
    image: <docker-image-url>
    restart: always
    volumes: 
      - lawuna_server_data:/app
    ports:
      - "5000:5000"
    command: gunicorn -w 3 -b 0.0.0.0:5000 main:app
  
volumes:
  lawuna_server_data:
```

When I check my logs in ECS the cause of the failure of the task is `ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: command failed with 32: failed to execute command to invoke EFS utils: mount.nfs4: Connection reset by peer`
