### ISSUE TITLE
More flexibility with merging arrays in x-aws-cloudformation overlays

### ISSUE THREAD

**Issue by FraserThompson** [docker/compose-cli#2160]
**Description**

To workaround the lack of sidecar support in docker compose files, I had the idea of simply adding in a definition for a new container to the ContainerDefinitions array on a generated TaskDefinition via the x-aws-cloudformation overlay.

However I found that if I add an element to a YAML array in the overlay, it will replace the entire array with my override rather than appending.

It would make this feature much more powerful if there was some way to control the way the YAML is merged.

It looks like the library used for this is kyaml from kubernetes? I couldn't find any documenation so I'm not sure if this is a feature which is already here, or if this is a feature request.

**Comment by JohnPreston** [comment]
Implemented in[ ECS Compose-X](https://docs.compose-x.io) since version 0.2, you can define a deploy label `ecs.task.family` that will logically group services together.
i.e.

```yaml
services:
  nginx:
    deploy:
      labels:
        ecs.task.family: frontend
  some-sidecar:
    deploy:
      labels:
        ecs.task.family: frontend
  backend: {}
```
will automatically merge these two (nginx, some-sidecar) into the one task definition.
All details in [these docs](https://docs.compose-x.io/syntax/compose_x/ecs.details/deploy.html)

Again, the objective here of compose-x is to remove the necessity to write CFN template for ECS services, and retain CFN syntax for every other aws resources that you want to create/use.
