### ISSUE TITLE
I can't specify on which subnet I would like service to run

### ISSUE THREAD

**Issue by komatom** [docker/compose-cli#2161]
Hi

in other words I am trying to run databases in 1 subnet, web serice in another subnet. I kind of can do this over  "x-aws-cloudformation:"
but I am having trouble with NFS access points, because they are created for all subnets per service, but I limit the service to 1 subnet and CloudFormation template roll backs and can't update.

So is there an option to specify for each service section to tie it to a subnet, and respectively from that list to be generated the NFSMount targets.

Thanks,
AK

**Comment by JohnPreston** [comment]
Hello both,

Hoping this will be helpful for you to keep docker-compose compatibility with more features that currently supported by this plugin.

You can do that with [ECS Compose-X](https://docs.compose-x.io): using [x-vpc](https://docs.compose-x.io/syntax/compose_x/vpc.html) via creating a new one or via Lookup for an existing VPC and its subnets, you can then define networks, the docker-compose way with `networks`, and map which network to run the services into, using `services.<service_name>.networks.[]`.

As for DB/ELB and such, these resources will have a `Subnets` parameter that you can use to specify which subnets defined in `x-vpc` you want to use.

Here are some examples that might be helpful: https://docs.compose-x.io/how_tos.html
Also, check out the [labs](https://labs.compose-x.io) which contain some real-life usage of compose-x inspired by deployments done for work.

Any requests/feedback, let me know!

**Comment by JohnPreston** [comment]
Hey. Sorry for "delay" in reply.

Here is what you are trying to do would look like using [ECS Compose-X](https://docs.compose-x.io) instead of this ECS plugin...

```yaml
version: '3.8'

# Define networks and map these to x-vpc Subnets, to use with the services

networks:
  application:
    x-vpc: AppSubnets
  storage:
    x-vpc: StorageSubnets

services:
  osticket:
    container_name: osticket-web
    image: osticket/osticket
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: secret
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - application
  db:
    container_name: osticket-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
    networks:
      - storage

# Just as an example, if you wanted to use RDS instead.

x-rds:
  my-db:
    MacroParameters:
      Engine: mariadb # Did not check the name
      EngineVersion: 10.4 # Did not check the engine version!
    Services:
      osticket:
        Access:
          DBCluster: RO # Allows rds:Describe on Cluster and Instances
        SecretsMappings: # Compose-X will generate a new Random username/password for the DB
          Mappings: # Map the key in the secret to the environment variable name your app needs
            host: MYSQL_HOST
            port: MYSQL_PORT
            username: MYSQL_USER
            password: MYSQL_PASSWORD
            dbname: MYSQL_DATABASE

x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: my-existing-vpc
    PublicSubnets:
      Tags:
        - Name: my-public-subnets
    AppSubnets:
      Tags:
        - Name: my-application-subnets
    StorageSubnets:
      Tags:
        - Name: my-db-storage-subnets

```

Does that help?

**Comment by xender69** [comment]
Thank you so much, I will try out your config without the RDS for the moment.  Will report back.

**Comment by xender69** [comment]
hi John,
Thank you for such a quick reply. So in order to use ecs compose-X, I would need to install python3 and initialize ecs-compose-x before I can use these commands in the docker compose file?

Does the below configuration look right?

```
version: '3.8'

# Define networks and map these to x-vpc Subnets, to use with the services

networks:
  application:
    x-vpc: AppSubnets
  storage:
    x-vpc: StorageSubnets

services:
  osticket:
    container_name: osticket-web
    image: osticket/osticket
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: secret
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - application
  db:
    container_name: osticket-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
    networks:
      - storage

x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: vpc-0603884f9eaf1ebb3
#    PublicSubnets: ** not used **
#      Tags:
#        - Name: my-public-subnets
#            - subnet-093223fe760e52016 #public subnet-1
#            - subnet-08120f88feb55e3f1 #public subnet-2
    AppSubnets:
      Tags:
        - Name: my-application-subnets
            - subnet-093223fe760e52016 #public subnet-1
            - subnet-08120f88feb55e3f1 #public subnet-2
    StorageSubnets:
      Tags:
        - Name: my-db-storage-subnets
            - subnet-0c68a298227d9c2e8 #private subnet-1
            - subnet-042cae15125ba9b1b #private subnet-2
```
Thank you again!!!

**Comment by xender69** [comment]
hi John,
I have installed python3 and ecs compose-X via
# Install in a virtual environment # Recommended
python3 -m venv venv
source venv/bin/activate
python3 -m pip install ecs-composex

So, will the code below work now for what I am trying to do?

```
version: '3.8'

# Define networks and map these to x-vpc Subnets, to use with the services

networks:
  application:
    x-vpc: AppSubnets
  storage:
    x-vpc: StorageSubnets

services:
  osticket:
    container_name: osticket-web
    image: osticket/osticket
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: secret
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - application
  db:
    container_name: osticket-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
    networks:
      - storage

x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: vpc-0603884f9eaf1ebb3
#    PublicSubnets: ** not used **
#      Tags:
#        - Name: my-public-subnets
#            - subnet-093223fe760e52016 #public subnet-1
#            - subnet-08120f88feb55e3f1 #public subnet-2
    AppSubnets:
      Tags:
        - Name: my-application-subnets
            - subnet-093223fe760e52016 #public subnet-1
            - subnet-08120f88feb55e3f1 #public subnet-2
    StorageSubnets:
      Tags:
        - Name: my-db-storage-subnets
            - subnet-0c68a298227d9c2e8 #private subnet-1
            - subnet-042cae15125ba9b1b #private subnet-2
```

Thank you so much!!!!
