### ISSUE TITLE
ACI: Improve volume syntax

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#560]
**Description**
Currently on ACI, volumes can be mapped to Azure file share. This implies you have an Azure storage account, and inside this account an azure file share (each with a name as identifier). 
You can use volumes in 2 ways : 
* `docker run -v storageAccount@fileShare:/target/path nginx` for single containers
* in compose files: 
```
myservice:
    image: xxx
    volumes:
      - mydata:/mount/testvolumes

volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: storageAccount
      storage_account_name: fileShare
```
Issues : 
1. the `run -v` syntax is not nice with the @ in the middle (a relicat from before when a storage account key was required)
2. ACI compose files do not allow short syntax. The compose parser (compose.go) checks if the volume spec is detected as a filePath, if not it expects it to map to a volume definition. 

**Proposal**
Discussing with @rumpl , we propose to change the run short syntax to : 
`docker run -v storageAccount/fileShare:/target/path nginx`

The short syntax will not be available in compose files, as it would require to format the short syntax exactly as a path (starting with `/`), that would be confusing. Compose allows short syntax on volumes only for path specs.

This does not block anything on the aws side when implementing volumes on EFS : 
* using the driver options in compose will let us define an EFS driver with any relevant option 
* we can arbitrarily decide to use a similar short syntax with `/token1/token2:target` to match what is required for EFS with several tokens in the source part of the volume spec
