### ISSUE TITLE
Allow user to select FARGATE_SPOT capacity provider

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#674]
initially reported by https://github.com/docker/ecs-plugin/issues/143
see https://aws.amazon.com/fr/blogs/aws/aws-fargate-spot-now-generally-available/

We should provide some way for end-user to select capacity provider, either `FARGATE` (default) or `FARGATE_SPOT`.

**Comment by flaviostutz** [comment]
Until this is not implemented, I've been using spot instances in ECS with docker compose by specifying an existing ECS cluster that is already configured with SPOT as provider (`x-aws-cluster`).

**Comment by tyronedd** [comment]
Hey @ndeloof hasn't this now landed? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-clustercapacityproviderassociations.html#aws-resource-ecs-clustercapacityproviderassociations--examples--Creating_a_cluster_capacity_provider_association_using_an_AWS_Fargate_capacity_provider.--yaml

**Comment by ndeloof** [comment]
@tyronedd yes indeed, need to define how to declare this in the compose file and check we can assign this in the produced cloudformation template. Contributions are welcome! :P

**Comment by briggySmalls** [comment]
Similarly, my "workaround" for now has been to tune the cloudformation template, by appending the following to my `docker-compose.yml`:

```
# Helper for removing the launch type from a service
x-no-launch-type: &no-launch-type
  Properties:
    LaunchType: null

# Cloudformation "tuning"
# See https://docs.docker.com/cloud/ecs-integration/#tuning-the-cloudformation-template
x-aws-cloudformation:
  Resources:
    # Use cheap fargate instances that may terminate suddenly
    # To do so we switch from using the old "Launch type" to specifying a capacity provider
    Cluster:
      Properties:
        CapacityProviders:
          - FARGATE_SPOT
        DefaultCapacityProviderStrategy:
          - CapacityProvider: FARGATE_SPOT
            Weight: 1
    # We must remove the default "launch type" on each service in order for the default strategy to kick-in
    MyDockerComposeService:
      <<: *no-launch-type
```
