### ISSUE TITLE
Configuring Target Group to Forward 443 to 80

### ISSUE THREAD

**Issue by ajlozier** [docker/compose-cli#693]
My initial `docker-compose.yml` file contained an entry for an nginx task, e.g.

```
  webserver:
    x-aws-pull_credentials: "xxxxx"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
```

This causes an additional target group to be created checking the health on port 443. Since I have not configured nginx to accept connections on port 443, nor an installed cert, the health checks of course fail.

What I instead want to do is configure the load balancer to forward connections to port 443 to port 80, which I believe is best practice.

Is there a way to specify this in the `docker-compose.yml` file, or is this currently a manual change I would need to make either directly or using the cloudformation template?
