### ISSUE TITLE
Configure autoscaling parameters

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#767]
**Description**

`x-aws-autoscaling` is already implemented but does not allow to pass autoscaling parameters.
Proposed syntax is:
```yaml
x-aws-autoscaling:
  memory: ..
  cpu: ..
  min: ..
  max: ..
```

`memory` and `cpu` are target percent and mutually exclusive. `max` is required
