### ISSUE TITLE
HTTPS Support for ECS Load Balancers

### ISSUE THREAD

**Issue by jdconley** [docker/compose-cli#775]
I'd like to be able to specify a TLS certificate from the AWS ACM that would configure a listener on the load balancer port 443 and appropriate inbound security rule. I do this on my own today after running `docker compose up` in the ecs context.

docker-compose.yml would look something like:

```
version: "3.8"
services:
    web:
        image: my_image_that_listens_for_http_on_port_8080
        x-aws-loadbalancer_certificate: arn:aws:acm:us-east-2:858246198183:certificate/[uuid]
        ports:
            - "443:8080"
```

**Comment by ndeloof** [comment]
Issue doing so is that we can't use `443:8080` port translation for service-to-service communication (services won't pass throught a load-balancer to connect to each other)
Having port mapping support for external communication but not for internal one would be error prone.

I have no idea yet how we could balance this with a reasonable and portable workaround.

**Comment by jdconley** [comment]
> Issue doing so is that we can't use `443:8080` port translation for service-to-service communication (services won't pass throught a load-balancer to connect to each other)
> Having port mapping support for external communication but not for internal one would be error prone.
> 
> I have no idea yet how we could balance this with a reasonable and portable workaround.

True, this short hand would be troublesome. This would be quite useful in AWS where the load balancer that compose-cli uses already supports HTTPS TLS with just a couple of CloudFormation configurations. Azure Front Door is similar.

Just a straw man here. Without modifying [ports](https://docs.docker.com/compose/compose-file/#ports) itself, though that might be ideal, like how swarm added "ingress", maybe something like this? And in this configuration the "published" version of the port would take precedence in CloudFormation, but the internal "8080" port would still be exposed and available to the host network.

```
version: "3.8"
services:
  web:
    image: my_image_that_listens_for_http_on_port_8080
    x-external-ingress:
      - driver: ecs
        target: 8080
        published: 443
        protocol: https
        certificate: arn:aws:acm:us-east-2:858246198183:certificate/[uuid]
    ports: 
      - "8080"
```
