### ISSUE TITLE
docker ps (with docker binar 0.1.22) throws an exception  

### ISSUE THREAD

**Issue by mreferre** [docker/compose-cli#790]
BUG REPORT INFORMATION
---------------------------------------------------

I am testing a compose file whose content is as follows ( all account IDs and ARNs have bene faked): 
```
version: "3.8"

x-aws-cluster: "docker2ecs-cluster" # my cluster 
x-aws-vpc: vpc-hdfgd67hjd # my VPC (default)
x-aws-loadbalancer: "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxx:loadbalancer/app/docker2ecs-LB/hdgshteykkl" # my ALB

services:
  docker2ecs:
    image: mreferre/docker2ecs:latest
    ports:
      - 80:80
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-2:xxxxxxxxx:secret:dockerhubAccessToken-hdhKdk"
    x-aws-logs_retention: 30
    x-aws-policies: 
      - "arn:aws:iam::aws:policy/AdministratorAccess" # IAM role is created with an Admin policy and assigned to the container
    deploy:
      replicas: 1
      update_config:
        x-aws-min_percent: 50 
        x-aws-max_percent: 300         
    secrets: 
      - preferences # my secret injected into the container (@ /run/secrets/preferences)
    networks: 
      - dmz
    
secrets:
  preferences:
    name: "arn:aws:secretsmanager:us-west-2:xxxxxxxxx:secret:PREFERENCES-Jhdhgdf" # my secret
    external: true

networks:
  dmz:
    external: true
    name: "sg-0179xxxxx9f29" # my SG (allow port 80) 
```

I am using Desktop Edge (latest which is version `2.4.1.0`). I am also brute forcing updating my setup to use the latest `docker` CLI release available today (`0.1.22`) on this repo. 

This stack deploys fine but a subsequent `docker compose ps` does not work (see below)

**Steps to reproduce the issue:**
```
➜  Downloads ./dockercloud/docker/docker compose up
[+] Running 11/11
 ⠿ downloads                        CREATE_COMPLETE                                                                                                                                 147.0s
 ⠿ Docker2ecsTCP80TargetGroup       CREATE_COMPLETE                                                                                                                                   0.0s
 ⠿ Docker2ecsTaskExecutionRole      CREATE_COMPLETE                                                                                                                                  18.0s
 ⠿ CloudMap                         CREATE_COMPLETE                                                                                                                                  47.0s
 ⠿ Dmz80Ingress                     CREATE_COMPLETE                                                                                                                                   1.0s
 ⠿ Docker2ecsTaskRole               CREATE_COMPLETE                                                                                                                                  17.0s
 ⠿ LogGroup                         CREATE_COMPLETE                                                                                                                                   3.0s
 ⠿ Docker2ecsTCP80Listener          CREATE_COMPLETE                                                                                                                                   0.0s
 ⠿ Docker2ecsTaskDefinition         CREATE_COMPLETE                                                                                                                                   3.0s
 ⠿ Docker2ecsServiceDiscoveryEntry  CREATE_COMPLETE                                                                                                                                   2.0s
 ⠿ Docker2ecsService                CREATE_COMPLETE                                                                                                                                  87.8s
➜  Downloads
``` 

**Describe the results you received:**

Using both the new `docker` binary as well as the old binary I am receiving wrong results. The new one throw an exception while the old one (still in path) does not show anything. 

New binary output:
```
➜  Downloads ./dockercloud/docker/docker compose ps 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/docker/compose-cli/ecs.sdk.DescribeService(0x2d705c0, 0xc00000e240, 0x2d80ae0, 0xc00000e258, 0x2d6e240, 0xc00000e268, 0x2d6eae0, 0xc00000e280, 0x2d6f2a0, 0xc00000e290, ...)
	github.com/docker/compose-cli/ecs/sdk.go:648 +0x87e
github.com/docker/compose-cli/ecs.(*ecsAPIService).Ps(0xc00059a3c0, 0x2d52cc0, 0xc00003acc0, 0xc00003edb0, 0x9, 0x8, 0x0, 0x203000, 0x0, 0x0)
	github.com/docker/compose-cli/ecs/ps.go:43 +0x1ef
github.com/docker/compose-cli/cli/cmd/compose.runPs(0x2d52cc0, 0xc00003acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3a13e00, 0x0, ...)
	github.com/docker/compose-cli/cli/cmd/compose/ps.go:57 +0x124
github.com/docker/compose-cli/cli/cmd/compose.psCommand.func1(0xc000572b00, 0x3a13e00, 0x0, 0x0, 0x0, 0x0)
	github.com/docker/compose-cli/cli/cmd/compose/ps.go:38 +0xb8
github.com/spf13/cobra.(*Command).execute(0xc000572b00, 0x3a13e00, 0x0, 0x0, 0xc000572b00, 0x3a13e00)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000342000, 0xc00003ac90, 0x25e05a0, 0x3a13e00)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.0.0/command.go:880
main.main()
	github.com/docker/compose-cli/cli/main.go:194 +0x96c
➜  Downloads
```

Old binary output:
```
➜  Downloads docker compose ps 
ID                  NAME                REPLICAS            PORTS
```

**Describe the results you expected:**
I would have expected to see the list of my deployment(s)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Old binary:
```
➜  Downloads docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

New binary:
```
➜  Downloads ./dockercloud/docker/docker version   
Client: Docker Engine - Community
 Cloud integration: 0.1.22
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
➜  Downloads docker context show
myecscontext
```

**Output of `docker info`:**

Docker info fails for the ecs context (probably correct?)

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
The backend cloud service I am using is Amazon ECS
