### ISSUE TITLE
"External secrets are not available to containers created by docker-compose"

### ISSUE THREAD

**Issue by mreferre** [docker/compose-cli#798]
My setup is similar to what I have used for [this issue](https://github.com/docker/compose-cli/issues/790). 

I am copying/pasting the compose file for convenience (everything else is also the same to issue #790). 
```
version: "3.8"

x-aws-cluster: "docker2ecs-cluster" # my cluster 
x-aws-vpc: vpc-hdfgd67hjd # my VPC (default)
x-aws-loadbalancer: "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxx:loadbalancer/app/docker2ecs-LB/hdgshteykkl" # my ALB

services:
  docker2ecs:
    image: mreferre/docker2ecs:latest
    ports:
      - 80:80
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-west-2:xxxxxxxxx:secret:dockerhubAccessToken-hdhKdk"
    x-aws-logs_retention: 30
    x-aws-policies: 
      - "arn:aws:iam::aws:policy/AdministratorAccess" # IAM role is created with an Admin policy and assigned to the container
    deploy:
      replicas: 1
      update_config:
        x-aws-min_percent: 50 
        x-aws-max_percent: 300         
    secrets: 
      - preferences # my secret injected into the container (@ /run/secrets/preferences)
    networks: 
      - dmz
    
secrets:
  preferences:
    name: "arn:aws:secretsmanager:us-west-2:xxxxxxxxx:secret:PREFERENCES-Jhdhgdf" # my secret
    external: true

networks:
  dmz:
    external: true
    name: "sg-0179xxxxx9f29" # my SG (allow port 80) 
```

When I try to `docker compose up` the same exact YAML with the `ecsLocal` context I get the following warning message (among a few others that are unrelated to this specific question): 

```
➜  Downloads docker compose up
....
WARNING: Service "docker2ecs" uses secret "preferences" which is external. External secrets are not available to containers created by docker-compose.
....
``` 

This is the context: 
```
➜  Downloads docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
ecsLocal *          ecs-local           ECS local endpoints                                                                           
myecscontext        ecs                 us-west-2         
```

The IAM admin role works fine because my demo container can access S3 but I am not able to source the secret I stored in Secrets Manager. From the `WARNING` message it feels like "by design" but I was expecting that retrieving a secret from SM would be a supported (useful?) local scenario (just like being able to get temporary AWS credentials - which works great).  

Or perhaps there are good reasons for not doing that which I am missing?
