### ISSUE TITLE
`docker compose up` shuts down and reports `Throttling: Rate exceeded`

### ISSUE THREAD

**Issue by cch1** [docker/compose-cli#853]
**Description**
A presumably basic `docker-compose.yml` can't be started -but it gets very close.

**Steps to reproduce the issue:**
1. I run the docker compose up: `docker compose -D -c chatalicious --project-name chatalicious up`
2. Docker starts and begins creating resources
3. After almost exactly five minutes, and after creating many resources and reporting "Running 46/48", docker reports "DELETE IN PROGRESS User Initiated". 
4. After another five  minutes or so, Docker reports:
```
Throttling: Rate exceeded
	status code: 400, request id: 93136ede-1097-41be-ab40-2a9db6f7eaa2
```
This is repeatable.

**Describe the results you received:**
The (two) containers are not running.

**Describe the results you expected:**
The containers (and associated resources) should be running.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 0.1.22
 Version:           20.10.0-beta1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        ac365d7
 Built:             Tue Oct 13 18:13:53 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0-beta1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       9c15e82
  Built:            Tue Oct 13 18:17:18 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context inspect chatalicious`:**  

```
[
    {
        "Name": "chatalicious",
        "Metadata": {
            "Description": "us-east-1",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Profile": "chatalicious.docker",
                "Region": "us-east-1"
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/cch1/.docker/contexts/meta/f513c4120ab5aa5ce3811f4725d6b4c81fd6aaaac53cddc2b78e4f2437edf2aa",
            "TLSPath": "/Users/cch1/.docker/contexts/tls/f513c4120ab5aa5ce3811f4725d6b4c81fd6aaaac53cddc2b78e4f2437edf2aa"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 12
 Server Version: 20.10.0-beta1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.39-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.94GiB
 Name: docker-desktop
 ID: Z6VH:WX6V:VJIZ:25WK:R4TQ:YKGU:XO4Z:FYU3:U4VV:FL2G:P5KA:FMAP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No blkio weight support
WARNING: No blkio weight_device support```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
This is pretty virgin AWS account and the IAM user whose credentials are associated with the context has been granted (temporarily) the AWS `AdministratorAccess` policy.

**Comment by cch1** [comment]
This is the compose file:
```
version: '3.8'
volumes:
  datomic-data:
    external: true
    name: fs-a042bb55
  datomic-logs:
    external: true
    name: fs-a142bb54

services:
  datomic:
    restart: always
    ports:
      # Document port usage
      - '4334'
      - '4335'
      - '4336'
    environment:
      DATOMIC_PASSWORD: "REDACTED"
      ADMIN_PASSWORD: "REDACTED"
      ALT_HOST: "datomic"
    volumes:
      - datomic-data:/data
      - datomic-logs:/logs
    image: 'akiel/datomic-free:latest'
  braid:
    depends_on:
      - datomic
    restart: always
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'
      - '6000:6000'
    environment:
      HTTP_PORT: "5000"
      MOBILE_PORT: "5001"
      API_PORT: "5002"
      REPL_PORT: "6000"
      HMAC_SECRET: "REDACTED"
      ENVIRONMENT: "prod"
      HTTP_ONLY: "true"
      DB_URL: "datomic:free://datomic:4334/braid?password=datomic"
      AWS_BUCKET: "chatalicious-braid"
      AWS_REGION: "us-east-1"
      AWS_ACCESS-KEY: "REDACTED"
      AWS_SECRET-KEY: "REDACTED"
    image: 'chatalicious_braid:latest'
    build:
      context: .
      dockerfile: Dockerfile
```
