### ISSUE TITLE
hostnames of sibling containers cannot be found: azure/aci and dns sidecar

### ISSUE THREAD

**Issue by pietelite** [docker/compose-cli#986]
When using `docker compose up` in the aci context, the containers instances are created appropriately but one container's request to another container with their special hostname cannot be resolved. That is, the `aci--dns--sidecar` displays all the hostnames correctly, but the container names nevertheless cannot be resolved. Instead, I must use the IP address of the container, which I input with an environment variable upon running `docker compose up` again.

This might be a problem with azure and not with this CLI

**Steps to reproduce the issue:**
1. Create an application which references the hostname 'db'
2. Create `docker-compose.yml` to build container 'webapp' using that application and another container called 'db' with a database image
3. Build container with `docker-compose build`
4. Switch contexts to your aci context with `docker context use myacicontext`
5. Push contexts to your registry with `docker-compose push`
6. Spin up containers with `docker compose up`

**Describe the results you received:**
Application 'webapp' fails with error message hostname 'db' cannot be resolved

**Describe the results you expected:**
Application 'webapp' should function normally, as if 'db' was the IP of the container group

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 78
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.27GiB
 Name: docker-desktop
 ID: 553H:NQN3:7637:RHIT:R5RS:QXLB:BL7L:CKJG:ICBP:HVRN:FODU:RAXQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Building locally, deploying using Azure ACI

**Comment by gtardif** [comment]
Did you use `container_name` in your compose file ? 
Using `container_name` with docker-compose has the side effect of adding also the container_name` as a network alias. This was not supported in ACI, will be supported with https://github.com/docker/compose-cli/pull/1124. 
(I can't see any other reason why the hostname would not be resolved, with the current dnssidecar, except network issues external to this cli)

**Comment by gtardif** [comment]
FYI, support for compose field `container_name` and associated network alias will ship very soon in the next Desktop release

**Comment by gtardif** [comment]
This is now available in Docker Desktop, shipped last week. 
I'll close this issue, feel free to re-open if you have more details on this and the issue is not fixed (if not related to `container_name` field in Compose file)

**Comment by damienwebdev** [comment]
I'm still seeing this as not working. I don't use the container name, YAML file looks like:


```
version : '3'

services:
  my-app:
    image: app-image:latest
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    restart: always
    networks:
      - frontend
      - backend
  ingress:
    image: nginx:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 0.5G
        reservations:
          cpus: '0.25'
          memory: 0.1G
    restart: OnFailure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    depends_on:
      - magento2
```

Execing onto these containers and doing:

```
nslookup nginx
nslookup my-app
```

Fails resolution. Access to the containers in the group over localhost works though. This may not be a `docker-compose` problem and may be an Azure problem, but I don't really have a PoC at Azure to prod.

**Comment by cons0l3** [comment]
> 
> 
> This is now available in Docker Desktop, shipped last week.
> I'll close this issue, feel free to re-open if you have more details on this and the issue is not fixed (if not related to `container_name` field in Compose file)

@gtardif could you please be more specific on which docker

> 
> 
> This is now available in Docker Desktop, shipped last week.
> I'll close this issue, feel free to re-open if you have more details on this and the issue is not fixed (if not related to `container_name` field in Compose file)

@gtardif could you please be more specific in which version of docker desktop the feature is available? thanks

**Comment by cons0l3** [comment]
@gtardif 

I am running 
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           aci-demo-context
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

with a docker-compose file 
```
# https://github.com/docker/compose-cli/issues/986
version : '3'
services:
  app:
    image: alpine:latest
    command: /bin/sh -c "/bin/hostname && /bin/ping db"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 0.2G
        reservations:
          cpus: '0.25'
          memory: 0.2G
  db:
    image: alpine:latest
    command: /bin/sh -c "/bin/hostname && /bin/ping app"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 0.2G
        reservations:
          cpus: '0.25'
          memory: 0.2G
```

the commandline `docker compose -f .\docker-compose-network-issues.yml -p network-issues up`

and receive in the logs:
- **app container:** ```wk-caas-08c47236fabb466caf01ac0b6f902bc9--1261cb87bc644a78611764
ping: bad address 'db'```
- **db container:** ```wk-caas-08c47236fabb466caf01ac0b6f902bc9--1261cb87bc644a78611764
ping: bad address 'app'```
- **aci--dns--sidecar: ** `Setting local hosts for app, db`

**Notice the the output of "hostname" on both containers is the same!**

I would have expected network reachability from one container to the other via compose service name. I would have expected different output for the "hostname".

I have used container_name in the docker-compose. no luck.

This bug is not solved.
